if(VARNAME)
  message(STATUS "Variable - ${VARNAME}: $ENV{${VARNAME}}")
else()
  message(STATUS "Stage: $ENV{Stage}")
  message(STATUS "Separator: $ENV{ListSeparator}")
  message(STATUS "List: $ENV{ListVar}")
endif()

if(MYLIST)
  message(STATUS "MYLIST:")
  foreach(__item IN LISTS MYLIST)
    message(STATUS "-- ${__item}")
  endforeach()
endif()
