
enable_language(C)
enable_language(CXX)

set_property(GLOBAL PROPERTY DEBUG_CONFIGURATIONS Debug Foo)

file(GENERATE OUTPUT GLOBAL_PROPERTY-generated.txt CONTENT "ENABLED_LANGUAGES=$<GLOBAL_PROPERTY:ENABLED_LANGUAGES>\nDEBUG_CONFIGURATIONS=$<GLOBAL_PROPERTY:DEBUG_CONFIGURATIONS>\n")
