include(RunCMake)

# Unity of size 1 doesn't make sense and shouldn't be created.
run_cmake(Unity1)
run_cmake(Unity2)
run_cmake(UnityBatchSize)
run_cmake(UnityGroup)
run_cmake(UnityIsolate)
run_cmake(UnitySubdirs)
run_cmake(UnitySubdirsIsolate)
run_cmake(DisableCaching)
run_cmake(DisableDistribution)
run_cmake(SetCompilerProps)
run_cmake(ImportedObjectLib)
run_cmake(InterfaceWithPrivateSource)
run_cmake(ObjectAndSharedLibs)
set(RunCMake_TEST_BINARY_DIR ${RunCMake_BINARY_DIR}/ObjectAndSharedLibs-build)
set(RunCMake_TEST_NO_CLEAN 1)
run_cmake_command(ObjectAndSharedLibs-build ${CMAKE_COMMAND} --build .)
