set(ENV{CMAKE_TEST_RUNCMAKE_EXECUTE_PROCESS_ENVIRONMENT} "kaese")
execute_process(
  COMMAND ${CMAKE_COMMAND} -E environment
  ENVIRONMENT_MODIFICATION
    "CMAKE_TEST_RUNCMAKE_EXECUTE_PROCESS_ENVIRONMENT=string_append:kuchen"
  )
