include(RunCMake)

run_cmake(WrongArgument)
run_cmake(InvalidArgument)
run_cmake(MissingArgument)
run_cmake(WrongScope)
run_cmake(EndMissing)
run_cmake(EndWithArgument)
run_cmake(EndAlone)
run_cmake(EndAloneWithArgument)

run_cmake(InvalidNesting1)
run_cmake(InvalidNesting2)
run_cmake(InvalidNesting3)
run_cmake(InvalidNesting4)
run_cmake(InvalidNesting5)
run_cmake(InvalidNesting6)

run_cmake(Scope)
run_cmake(Scope-VARIABLES)
run_cmake(Scope-POLICIES)
run_cmake(Workflows)
