include(RunCMake)

run_cmake(LINK_LANG_AND_ID-add_custom_target)
run_cmake(LINK_LANG_AND_ID-add_custom_command)
run_cmake(LINK_LANG_AND_ID-install)
run_cmake(LINK_LANG_AND_ID-target_sources)
run_cmake(LINK_LANG_AND_ID-add_executable)
run_cmake(LINK_LANG_AND_ID-add_library)
run_cmake(LINK_LANG_AND_ID-add_test)
run_cmake(LINK_LANG_AND_ID-unknown-lang)
run_cmake(LINK_LANG_AND_ID-wrong-usage1)
run_cmake(LINK_LANG_AND_ID-wrong-usage2)
run_cmake(LINK_LANG_AND_ID-wrong-usage3)
run_cmake(LINK_LANG_AND_ID-file_generate)
