
if (NOT VALID_LANG)
  set (VALID_LANG C)
endif()
if (NOT INVALID_LANG)
  set (INVALID_LANG CXX)
endif()
if (NOT TYPE)
  set (TYPE EXE)
endif()

if (NOT actual_stdout MATCHES "DIR_${VALID_LANG}_${TYPE}")
  set (RunCMake_TEST_FAILED "Not found expected 'DIR_${VALID_LANG}_${TYPE}'.")
endif()
if (actual_stdout MATCHES "DIR_${INVALID_LANG}_${TYPE}")
  if (RunCMake_TEST_FAILED)
    string (APPEND RunCMake_TEST_FAILED "\n")
  endif()
  string (APPEND RunCMake_TEST_FAILED "Found unexpected 'DIR_${INVALID_LANG}_${TYPE}'.")
endif()
