include(RunCMake)

run_cmake(Example)
run_cmake(VERSION-SKIP)
run_cmake(VERSION-KEEP)
run_cmake(VARIABLE-SKIP)
run_cmake(VARIABLE-KEEP)
run_cmake(ARGUMENT-SKIP)
run_cmake(ARGUMENT-KEEP)
run_cmake(DifferentScope)
