unset(ENV{UNSET_THEN_EMPTY})
set(ENV{UNSET_THEN_EMPTY} "")
if(DEFINED ENV{UNSET_THEN_EMPTY})
  message(STATUS "ENV{UNSET_THEN_EMPTY} is defined to '$ENV{UNSET_THEN_EMPTY}'")
else()
  message(STATUS "ENV{UNSET_THEN_EMPTY} is not defined")
endif()

set(ENV{SET_THEN_EMPTY} "set")
set(ENV{SET_THEN_EMPTY} "")
if(DEFINED ENV{SET_THEN_EMPTY})
  message(STATUS "ENV{SET_THEN_EMPTY} is defined to '$ENV{SET_THEN_EMPTY}'")
else()
  message(STATUS "ENV{SET_THEN_EMPTY} is not defined")
endif()
