include(RunCMake)
list(APPEND RunCMake_TEST_OPTIONS -Wno-experimental)

if(NOT RunCMake_GENERATOR MATCHES "Xcode")
  if(RunCMake_GENERATOR_IS_MULTI_CONFIG)
    list(APPEND RunCMake_TEST_OPTIONS -DCMAKE_CONFIGURATION_TYPES=Release)
  else()
    list(APPEND RunCMake_TEST_OPTIONS -DCMAKE_BUILD_TYPE=Release)
  endif()
  if(SYCL_TEST_CASE STREQUAL "Build")
    set(RunCMake_TEST_BINARY_DIR "${RunCMake_BINARY_DIR}")
    run_cmake(FileSet)
    set(RunCMake_TEST_NO_CLEAN 1)
    run_cmake_command(FileSet-build "${CMAKE_COMMAND}" --build . --config Release)
    return()
  endif()
  unset(RunCMake_TEST_NO_CLEAN)
  set(RunCMake_TEST_BINARY_DIR "${RunCMake_BINARY_DIR}/export")
  run_cmake_with_options(FileSetExport ${RunCMake_TEST_OPTIONS}
    "--install-prefix=${RunCMake_TEST_BINARY_DIR}/install")
  set(RunCMake_TEST_NO_CLEAN 1)
  run_cmake_command(FileSetExport-install "${CMAKE_COMMAND}" --install . --config Release)
  unset(RunCMake_TEST_NO_CLEAN)
  set(RunCMake_TEST_BINARY_DIR "${RunCMake_BINARY_DIR}/import")
  run_cmake(FileSetImport)
  set(RunCMake_TEST_NO_CLEAN 1)
  run_cmake_command(FileSetImport-build "${CMAKE_COMMAND}" --build . --config Release)
endif()
