# Automatically generated by CMake's FetchContent module.
# Do not edit this file, it will be regenerated every time CMake runs.

# Version not available, assuming it is compatible
set(PACKAGE_VERSION_COMPATIBLE TRUE)
