file(GLOB junit_xml_file "${RunCMake_TEST_BINARY_DIR}/junit.xml")
if(junit_xml_file)
  file(READ "${junit_xml_file}" junit_xml LIMIT 4096)
  if(NOT "${junit_xml}" MATCHES "tests=\"5\"")
    set(RunCMake_TEST_FAILED "tests=\"5\" not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "failures=\"1\"")
    set(RunCMake_TEST_FAILED "failures=\"1\" not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "disabled=\"1\"")
    set(RunCMake_TEST_FAILED "disabled=\"1\" not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "skipped=\"2\"")
    set(RunCMake_TEST_FAILED "skipped=\"2\" not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "<system-out>hello world")
    set(RunCMake_TEST_FAILED "<system-out>hello world not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "<system-out>Disabled")
    set(RunCMake_TEST_FAILED "<system-out>Disabled not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "<skipped message=\"Unable to find executable\"/>")
    set(RunCMake_TEST_FAILED "<skipped message=\"Unable to find executable\"/> not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "<system-out>Unable to find executable:")
    set(RunCMake_TEST_FAILED "<system-out>Unable to find executable: not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "<skipped message=\"SKIP_REGULAR_EXPRESSION_MATCHED\"/>")
    set(RunCMake_TEST_FAILED "<skipped message=\"SKIP_REGULAR_EXPRESSION_MATCHED\"/> not found when expected")
  endif()
  if(NOT "${junit_xml}" MATCHES "<system-out>please skip")
    set(RunCMake_TEST_FAILED "<system-out>please skip not found when expected")
  endif()
else()
  set(RunCMake_TEST_FAILED "junit.xml not found")
endif()
