MESSAGE("This is install script 4.")
IF(INSTALL_SCRIPT_3_DID_RUN)
  MESSAGE("Install script ordering works.")
ELSE(INSTALL_SCRIPT_3_DID_RUN)
  MESSAGE(FATAL_ERROR "Install script 3 did not run before install script 4.")
ENDIF(INSTALL_SCRIPT_3_DID_RUN)
IF(INSTALL_CODE_WITH_COMPONENT_DID_RUN)
  MESSAGE("Install code ordering works.")
ELSE(INSTALL_CODE_WITH_COMPONENT_DID_RUN)
  MESSAGE(FATAL_ERROR "Install script 4 did not run after install with component code.")
ENDIF(INSTALL_CODE_WITH_COMPONENT_DID_RUN)

IF(CMAKE_INSTALL_COMPONENT)
IF(NOT "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")
  MESSAGE("CMAKE_INSTALL_COMPONENT=\"${CMAKE_INSTALL_COMPONENT}\"")
  MESSAGE(FATAL_ERROR "Install script 4 should only run for \"Development\" INSTALL COMPONENT.")
ENDIF(NOT "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Development")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "${CMAKE_INSTALL_PREFIX}/MyTest/InstallScript4Out.cmake"
  "SET(CMAKE_INSTALL_SCRIPT_4_DID_RUN 1)\n"
  )
