macro(test_target_property PROP)
  add_custom_target(CustomTarget)
  set_property(TARGET CustomTarget PROPERTY ${PROP} x)
  set_property(TARGET CustomTarget PROPERTY ${PROP})
  set_property(TARGET CustomTarget APPEND PROPERTY ${PROP})
  set_property(TARGET CustomTarget PROPERTY ${PROP} a)
  set_property(TARGET CustomTarget APPEND PROPERTY ${PROP} "")
  set_property(TARGET CustomTarget APPEND PROPERTY ${PROP} b c)
  set_property(TARGET CustomTarget APPEND PROPERTY ${PROP})
  set_property(TARGET CustomTarget APPEND PROPERTY ${PROP} "d;;e")
  get_property(val TARGET CustomTarget PROPERTY ${PROP})
  message(STATUS "Target ${PROP} is '${val}'")
endmacro()
