project(ProjectCompatVersionTest VERSION 1.5.0 COMPAT_VERSION 1.0.0 LANGUAGES)
if(NOT PROJECT_COMPAT_VERSION)
  message(FATAL_ERROR "PROJECT_COMPAT_VERSION expected to be set")
endif()
if(NOT CMAKE_PROJECT_COMPAT_VERSION)
  message(FATAL_ERROR "CMAKE_PROJECT_COMPAT_VERSION expected to be set")
endif()
if(NOT ProjectCompatVersionTest_COMPAT_VERSION)
  message(FATAL_ERROR "ProjectCompatVersionTest_COMPAT_VERSION expected to be set")
endif()
message(STATUS "PROJECT_COMPAT_VERSION=${PROJECT_COMPAT_VERSION}")
message(STATUS "CMAKE_PROJECT_COMPAT_VERSION=${CMAKE_PROJECT_COMPAT_VERSION}")
message(STATUS "ProjectCompatVersionTest_COMPAT_VERSION=${ProjectCompatVersionTest_COMPAT_VERSION}")
