# no project() call, includer already calls project(${RunCMake_TEST} NONE)
if(NOT DEFINED PROJECT_IS_TOP_LEVEL)
  message(FATAL_ERROR "PROJECT_IS_TOP_LEVEL is not defined")
endif()
if(NOT DEFINED "CACHE{${RunCMake_TEST}_IS_TOP_LEVEL}")
  message(FATAL_ERROR "IsTopLevel_IS_TOP_LEVEL is not defined")
endif()
message(STATUS "PROJECT_IS_TOP_LEVEL=${PROJECT_IS_TOP_LEVEL}")
message(STATUS "${RunCMake_TEST}_IS_TOP_LEVEL=${${RunCMake_TEST}_IS_TOP_LEVEL}")
