SET (CTEST_PROJECT_NAME "CMake")
SET (CTEST_NIGHTLY_START_TIME "21:00:00 EDT")

MACRO(SET_IF_NOT_SET var val)
  IF(NOT DEFINED "${var}")
    SET("${var}" "${val}")
  ENDIF(NOT DEFINED "${var}")
ENDMACRO(SET_IF_NOT_SET)

SET_IF_NOT_SET(CTEST_DROP_METHOD "http")
IF(CTEST_DROP_METHOD STREQUAL "http")
  SET (CTEST_DROP_SITE "public.kitware.com")
  SET (CTEST_DROP_LOCATION "/cgi-bin/HTTPUploadDartFile.cgi")
  SET (CTEST_TRIGGER_SITE "http://${CTEST_DROP_SITE}/cgi-bin/Submit-CMake-TestingResults.cgi")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")

IF(CTEST_DROP_METHOD STREQUAL "xmlrpc")
  SET (CTEST_DROP_SITE "http://www.na-mic.org:8081")
  SET (CTEST_DROP_LOCATION "CMake")
  SET (CTEST_TRIGGER_SITE "not used")
  SET (COMPRESS_SUBMISSION ON)
ENDIF(CTEST_DROP_METHOD STREQUAL "xmlrpc")

