try_run(RUN_RESULT COMPILE_RESULT
  SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/ConfigureLog-bad.c
  )

try_run(RUN_RESULT COMPILE_RESULT
  SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/ConfigureLog-test.c
  )

try_run(RUN_RESULT COMPILE_RESULT
  SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/ConfigureLog-test.c
  RUN_OUTPUT_VARIABLE RUN_OUTPUT
  )

try_run(RUN_RESULT COMPILE_RESULT
  SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/ConfigureLog-test.c
  RUN_OUTPUT_STDOUT_VARIABLE RUN_STDOUT
  RUN_OUTPUT_STDERR_VARIABLE RUN_STDERR
  )
