find_package(UseComponents COMPONENTS Comp1 Comp2 OPTIONAL_COMPONENTS Comp3)

if (NOT UseComponents_FOUND)
  message (FATAL_ERROR "package UseComponents Not Found.")
endif()
if (NOT UseComponents_Comp1_FOUND)
  message (FATAL_ERROR "package UseComponents, component Comp1 not found.")
endif()
if (NOT UseComponents_Comp2_FOUND)
  message (FATAL_ERROR "package UseComponents, component Comp2 not found.")
endif()
if (UseComponents_Comp3_FOUND)
  message (FATAL_ERROR "package UseComponents, component Comp2 unexpectedly found.")
endif()
