set(d "/long/path/to/directory")
foreach(i RANGE 11)
  string(APPEND d "${d}")
endforeach()
string(LENGTH "${d}" dl)
if(IS_DIRECTORY "${d}/")
  message(FATAL_ERROR "Directory should not exist!")
else()
  message(STATUS "Directory path with length ${dl} correctly does not exist.")
endif()
if(IS_DIRECTORY "")
  message(FATAL_ERROR "IS_DIRECTORY \"\" should not exist")
endif()
