set(PROCESSORS 2)
set(CVS_COMMAND /vol/local/bin/cvs)
set(HOST "sshserv.centers.ihost.com" )
set(EXTRA_HOP "rsh v60n177" )
set(MAKE "make")
set(CC "xlc")
set(CXX "xlC")
set(INITIAL_CACHE "CMAKE_BUILD_TYPE:STRING=Release")
get_filename_component(path "${CMAKE_CURRENT_LIST_FILE}" PATH)
include(${path}/release_cmake.cmake)
