add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
export(EXPORT foo LOWER_CASE_FILE)
export(EXPORT foo APPENDIX test)
export(EXPORT foo VERSION 1.0)
export(EXPORT foo DESCRIPTION "Test")
export(EXPORT foo HOMEPAGE_URL "example.com")
export(EXPORT foo DEFAULT_TARGETS foo)
export(EXPORT foo DEFAULT_CONFIGURATIONS Release)
export(EXPORT foo PROJECT foo)
export(EXPORT foo NO_PROJECT_METADATA)
