add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
set(args EXPORT foo PACKAGE_INFO foo)
export(${args} APPENDIX)
export(${args} VERSION)
export(${args} COMPAT_VERSION)
export(${args} VERSION_SCHEMA)
export(${args} LICENSE)
export(${args} DEFAULT_LICENSE)
export(${args} DESCRIPTION)
export(${args} HOMEPAGE_URL)
export(${args} DEFAULT_TARGETS)
export(${args} DEFAULT_CONFIGURATIONS)
export(${args} PROJECT)
export(${args} LICENSE "" DEFAULT_LICENSE "")
