add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
set(args PACKAGE_INFO foo EXPORT foo APPENDIX test)
export(${args} VERSION 1.0)
export(${args} LICENSE "BSD-3-Clause AND CC-BY-SA-4.0")
export(${args} DESCRIPTION "Test")
export(${args} HOMEPAGE_URL "example.com")
export(${args} DEFAULT_TARGETS foo)
export(${args} DEFAULT_CONFIGURATIONS Release)
export(${args} PROJECT foo)
