add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)

export(EXPORT foo
  PACKAGE_INFO foo1
  VERSION 1.0)

export(EXPORT foo
  PACKAGE_INFO foo2
  VERSION 1.5
  COMPAT_VERSION 1.0)

export(EXPORT foo
  PACKAGE_INFO foo3
  VERSION 1.0
  VERSION_SCHEMA simple)
