file(GET_RUNTIME_DEPENDENCIES
  RESOLVED_DEPENDENCIES_VAR
  UNRESOLVED_DEPENDENCIES_VAR
  CONFLICTING_DEPENDENCIES_PREFIX
  BUNDLE_EXECUTABLE
  EXECUTABLES
  LIBRARIES
  MODULES
  DIRECTORIES
  PRE_INCLUDE_REGEXES
  PRE_EXCLUDE_REGEXES
  POST_INCLUDE_REGEXES
  POST_EXCLUDE_REGEXES
  POST_INCLUDE_FILES
  POST_EXCLUDE_FILES
  )
message(FATAL_ERROR "This message should not be displayed")
