include(RunCMake)

set(SKIP_TESTS 0)
if("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU" AND "${CMAKE_CXX_COMPILER_VERSION}" VERSION_LESS 4.2)
  set(SKIP_TESTS 1)
endif()
if (CMAKE_CXX_COMPILER_ID MATCHES Watcom
    OR CMAKE_SYSTEM_NAME MATCHES IRIX64
    OR CMAKE_CXX_COMPILER_ID MATCHES HP
    OR CMAKE_CXX_COMPILER_ID MATCHES XL
    OR CMAKE_CXX_COMPILER_ID MATCHES SunPro)
  set(SKIP_TESTS 1)
endif()

if (NOT SKIP_TESTS)
  run_cmake(PropertyTypo)
endif()
