unset(CMAKE_EXPERIMENTAL_MAPPED_PACKAGE_INFO)
set(CMAKE_INSTALL_EXPORTS_AS_PACKAGE_INFO foo:)

add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
install(EXPORT foo FILE foo-targets.cmake DESTINATION .)
