
set_property(GLOBAL PROPERTY COMMA_LIST "AA,BB")
set_property(GLOBAL PROPERTY CMAKE_LIST "CC;DD")
set_property(GLOBAL PROPERTY MIX_LIST "EE,FF;GG")

file(GENERATE OUTPUT list-conversion-generated.txt CONTENT "$<ARGS:$<GLOBAL_PROPERTY:COMMA_LIST>>|$<ARGS:$<GLOBAL_PROPERTY:CMAKE_LIST>>|$<ARGS:$<GLOBAL_PROPERTY:MIX_LIST>>")
