add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
install(
  PACKAGE_INFO foo
  DESTINATION cps
  EXPORT foo
  VERSION 1.2.3
  VERSION_SCHEMA simple
  COMPAT_VERSION 1.2.0
  DEFAULT_TARGETS foo
  DEFAULT_CONFIGURATIONS release debug
  )
