#include "cmCPackDocumentMacros.h"

void cmCPackDocumentMacros::GetMacrosDocumentation(
        std::vector<cmDocumentationEntry>& v)
{
    cmDocumentationEntry e("cpack_add_component",
            "Describes a CPack installation component "
            "named by the COMPONENT argument to a CMake INSTALL command.",
            "       cpack_add_component(compname\n"
            "                          [DISPLAY_NAME name]\n"
            "                          [DESCRIPTION description]\n"
            "                          [HIDDEN | REQUIRED | DISABLED ]\n"
            "                          [GROUP group]\n"
            "                          [DEPENDS comp1 comp2 ... ]\n"
            "                          [INSTALL_TYPES type1 type2 ... ]\n"
            "                          [DOWNLOADED]\n"
            "                          [ARCHIVE_FILE filename])\n"
            "\n"
            "The cmake_add_component command describes an installation"
            "component, which the user can opt to install or remove as part of"
            " the graphical installation process. compname is the name of the "
            "component, as provided to the COMPONENT argument of one or more "
            "CMake INSTALL commands."
            "\n"
          "DISPLAY_NAME is the displayed name of the component, used in "
          "graphical installers to display the component name. This value "
          "can be any string."
          "\n"
          "DESCRIPTION is an extended description of the component, used in "
          "graphical installers to give the user additional information about "
          "the component. Descriptions can span multiple lines using \"\\n\" "
          " as the line separator. Typically, these descriptions should be no "
          "more than a few lines long."
          "\n"
          "HIDDEN indicates that this component will be hidden in the "
          "graphical installer, so that the user cannot directly change "
          "whether it is installed or not."
          "\n"
          "REQUIRED indicates that this component is required, and therefore "
          "will always be installed. It will be visible in the graphical "
          "installer, but it cannot be unselected. (Typically, required "
          "components are shown greyed out)."
          "\n"
          "DISABLED indicates that this component should be disabled "
          "(unselected) by default. The user is free to select this component "
          "for installation, unless it is also HIDDEN."
          "\n"
          "DEPENDS lists the components on which this component depends. If "
          "this component is selected, then each of the components listed "
          "must also be selected. The dependency information is encoded "
          "within the installer itself, so that users cannot install "
          "inconsistent sets of components."
          "\n"
          "GROUP names the component group of which this component is a "
          "part. If not provided, the component will be a standalone "
          "component, not part of any component group. Component groups are "
          "described with the cpack_add_component_group command, detailed"
          "below."
          "\n"
          "INSTALL_TYPES lists the installation types of which this component "
          "is a part. When one of these installations types is selected, this "
          "component will automatically be selected. Installation types are"
          "described with the cpack_add_install_type command, detailed below."
          "\n"
          "DOWNLOADED indicates that this component should be downloaded "
          "on-the-fly by the installer, rather than packaged in with the "
          "installer itself. For more information, see the "
          "cpack_configure_downloads command."
          "\n"
          "ARCHIVE_FILE provides a name for the archive file created by CPack "
          "to be used for downloaded components. If not supplied, CPack will "
          "create a file with some name based on CPACK_PACKAGE_FILE_NAME and "
          "the name of the component. See cpack_configure_downloads for more "
          "information."
);

    v.push_back(e);
}
