add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
set(args PACKAGE_INFO test EXPORT foo)
install(${args} APPENDIX)
install(${args} VERSION)
install(${args} COMPAT_VERSION)
install(${args} VERSION_SCHEMA)
install(${args} LICENSE)
install(${args} DEFAULT_LICENSE)
install(${args} DESCRIPTION)
install(${args} HOMEPAGE_URL)
install(${args} DEFAULT_TARGETS)
install(${args} DEFAULT_CONFIGURATIONS)
install(${args} PROJECT)
install(${args} LICENSE "" DEFAULT_LICENSE "")
