add_library(foo INTERFACE)
install(TARGETS foo EXPORT foo DESTINATION .)
set(args PACKAGE_INFO test EXPORT foo APPENDIX test)
install(${args} VERSION 1.0)
install(${args} LICENSE "BSD-3-Clause AND CC-BY-SA-4.0")
install(${args} DESCRIPTION "Test")
install(${args} HOMEPAGE_URL "example.com")
install(${args} DEFAULT_TARGETS foo)
install(${args} DEFAULT_CONFIGURATIONS test)
install(${args} PROJECT foo)
