include(ExternalProject)
ExternalProject_Add(Sub
  SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/Sub"
  TMP_DIR "${CMAKE_CURRENT_BINARY_DIR}/tmp"
  CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/caller"
  DOWNLOAD_COMMAND ""
)
