function(check_genex expected actual)
  if(NOT expected STREQUAL actual)
    string(APPEND RunCMake_TEST_FAILED "Expected DLLs:\n")
    foreach(dll IN LISTS expected)
      string(APPEND RunCMake_TEST_FAILED "  ${dll}\n")
    endforeach()
    string(APPEND RunCMake_TEST_FAILED "Actual DLLs:\n")
    foreach(dll IN LISTS actual)
      string(APPEND RunCMake_TEST_FAILED "  ${dll}\n")
    endforeach()
  endif()
  set(RunCMake_TEST_FAILED "${RunCMake_TEST_FAILED}" PARENT_SCOPE)
endfunction()

include("${RunCMake_TEST_BINARY_DIR}/dlls.cmake")
