if(NOT EXISTS "${Data}")
  message(SEND_ERROR "Input file:\n  ${Data}\n" "does not exist!")
endif()
if(EXISTS "${AdjacentHash}")
  message(SEND_ERROR "Adjacent hash record exists but should not:\n  ${AdjacentHash}")
endif()
if(NOT EXISTS "${StateHash}")
  message(SEND_ERROR "State-root hash record is missing:\n  ${StateHash}")
endif()
