include(RunCMake)

run_cmake(AngleBracketsContent)
run_cmake(BadArgOutput)
run_cmake(BadArgContent)
run_cmake(BadArgGeneratorExpressionOutput)
run_cmake(UnrecognizedArgs)
run_cmake(DirOutput)
run_cmake(NewLineStyle-NoArg)
run_cmake(NewLineStyle-ValidArg)
run_cmake(NewLineStyle-WrongArg)
run_cmake(NoArgOutput)
run_cmake(NoArgContent)
run_cmake(SubDir)
run_cmake(AtOnly)
run_cmake(EscapeQuotes)
