include(Compiler/Clang)
__compiler_clang(SYCL)
__compiler_clang_cxx_standards(SYCL)

if(NOT CMAKE_SYCL_COMPILER_ID STREQUAL "AdaptiveCpp")
  set(_CMAKE_SYCL_REQUIRED_FLAG "-fsycl")
  foreach(std IN ITEMS 98 11 14)
    unset(CMAKE_SYCL${std}_STANDARD_COMPILE_OPTION)
    unset(CMAKE_SYCL${std}_EXTENSION_COMPILE_OPTION)
  endforeach()
  if(CMAKE_SYCL_COMPILER_VERSION VERSION_GREATER_EQUAL 24)
    set(CMAKE_SYCL_COMPILE_OPTIONS_SEPARABLE_COMPILATION_ON "-fgpu-rdc")
    set(CMAKE_SYCL_COMPILE_OPTIONS_SEPARABLE_COMPILATION_OFF "-fno-gpu-rdc")
  endif()
  set(CMAKE_SYCL_COMPILER_HAS_DEVICE_LINK_PHASE FALSE)
endif()

set(CMAKE_SYCL_COMPILE_OPTIONS_VISIBILITY_INLINES_HIDDEN
  "-fvisibility-inlines-hidden")

set(CMAKE_SYCL_COMPILER_PREDEFINES_COMMAND "${CMAKE_SYCL_COMPILER}")
if(CMAKE_SYCL_COMPILER_ARG1)
  separate_arguments(_COMPILER_ARGS NATIVE_COMMAND "${CMAKE_SYCL_COMPILER_ARG1}")
  list(APPEND CMAKE_SYCL_COMPILER_PREDEFINES_COMMAND ${_COMPILER_ARGS})
  unset(_COMPILER_ARGS)
endif()
if(CMAKE_SYCL_COMPILER_TARGET)
  if(CMAKE_SYCL_COMPILER_VERSION VERSION_LESS 3.4.0)
    list(APPEND CMAKE_SYCL_COMPILER_PREDEFINES_COMMAND
      "-target" "${CMAKE_SYCL_COMPILER_TARGET}")
  else()
    list(APPEND CMAKE_SYCL_COMPILER_PREDEFINES_COMMAND
      "--target=${CMAKE_SYCL_COMPILER_TARGET}")
  endif()
endif()
list(APPEND CMAKE_SYCL_COMPILER_PREDEFINES_COMMAND
  ${_CMAKE_SYCL_REQUIRED_FLAG} "-x" "c++" "-w" "-dM" "-E"
  "${CMAKE_ROOT}/Modules/CMakeSYCLCompilerABI.sycl")
