SET(CMAKE_ASM_VERBOSE_FLAG "-v")

SET(CMAKE_ASM_FLAGS_INIT "")
SET(CMAKE_ASM_FLAGS_DEBUG_INIT "-g")
SET(CMAKE_ASM_FLAGS_MINSIZEREL_INIT "-Os -DNDEBUG")
SET(CMAKE_ASM_FLAGS_RELEASE_INIT "-O3 -DNDEBUG")
SET(CMAKE_ASM_FLAGS_RELWITHDEBINFO_INIT "-O2 -g")

IF(UNIX)
  SET(CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S)
ELSE(UNIX)
  SET(CMAKE_ASM_SOURCE_FILE_EXTENSIONS asm)
ENDIF(UNIX)
