set(ENV_PATH "$ENV{PATH}")
set(ENV{PATH} "")
foreach(path "/does_not_exist" "/include" "")
  unset(PrefixInPATH_File CACHE)
  set(CMAKE_PREFIX_PATH "${CMAKE_CURRENT_SOURCE_DIR}${path}")
  find_file(PrefixInPATH_File NAMES PrefixInPATH.h)
  message(STATUS "PrefixInPATH_File='${PrefixInPATH_File}'")
endforeach()

set(CMAKE_FIND_USE_CMAKE_PATH OFF)
set(CMAKE_PREFIX_PATH )
foreach(path "/does_not_exist" "/include" "")
  unset(PrefixInPATH_File CACHE)
  set(CMAKE_PREFIX_PATH "${CMAKE_CURRENT_SOURCE_DIR}${path}")
  find_file(PrefixInPATH_File NAMES PrefixInPATH.h)
  message(STATUS "PrefixInPATH_File='${PrefixInPATH_File}'")
endforeach()
set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH ON)
set(ENV{PATH} "${ENV_PATH}")
