trigger:
  branches:
    include:
    - cmake-daemon
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/cmake-daemon
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
parameters:
- name: VSInsertion
  type: string
  default: false
variables:
- name: VSInsertion
  value: ${{parameters.VSInsertion}}
- name: BuildConfiguration
  value: RelWithDebInfo
- name: BuildPlatform
  value: Any CPU
- name: CMakeBuildDirectory
  value: $(Build.ArtifactStagingDirectory)/build
- name: CMakeInstallDirectory
  value: $(Build.ArtifactStagingDirectory)/output
- name: Codeql.Enabled
  value: true
- name: DisableDockerDetector
  value: true
- name: PackagingSolutionRoot
  value: $(Build.ArtifactStagingDirectory)/VSInsertion/Packaging
- name: PYTHONUTF8
  value: 1
- name: SigningSolutionRoot
  value: $(Build.ArtifactStagingDirectory)/VSInsertion/Signing
- name: SymbolsDirectory
  value: $(Build.ArtifactStagingDirectory)/symbols
- name: TeamName
  value: vcls
- name: TeamEmail
  value: cmaketools@microsoft.com
- name: ArchiveDir
  value: $(Build.ArtifactStagingDirectory)/archive
- name: 
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\VSInsertion\credscan.gdnsuppress # for third party cmake public source files
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Job_x64
        displayName: CMake x64 Build and Test
        timeoutInMinutes: 360
        cancelTimeoutInMinutes: 1
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish CMake x64 Artifact'
            targetPath: $(ArchiveDir)
            artifactName: CMakeX64
        steps:
        - checkout: self
          clean: true
          fetchTags: false
          persistCredentials: True
        - task: CMake@1
          name: CMake1
          displayName: CMake x64 Cache Generation
          inputs:
            cwd: $(CMakeBuildDirectory)
            cmakeArgs: -DCMAKE_INSTALL_PREFIX:PATH=$(CMakeInstallDirectory) -DCMAKE_CONFIGURATION_TYPES=$(BuildConfiguration) -DCMake_VERSION_MICROSOFT_SCHEME=true -DCMake_VERSION_NO_GIT=true -DMicrosoft_CMake_VERSION_PATCH=$(Build.BuildNumber) $(Build.SourcesDirectory) -DCMAKE_CXX_FLAGS_INIT="/W3 /Qspectre /guard:cf /ZH:SHA_256" -DCMAKE_C_FLAGS_INIT="/W3 /Qspectre /guard:cf /ZH:SHA_256" -DCMAKE_EXE_LINKER_FLAGS_INIT="/incremental:no /profile /guard:cf /CETCOMPAT" -S $(Build.SourcesDirectory) -B $(CMakeBuildDirectory) -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_ZIP=ON -DCPACK_PACKAGE_FILE_NAME=cmake_install_x64
        - task: CMake@1
          name: CMake2
          displayName: CMake x64 Build Install and Package
          inputs:
            cwd: $(CMakeBuildDirectory)
            cmakeArgs: --build . --target package install --config $(BuildConfiguration) -- -m
        # - task: CmdLine@1
        #   name: CmdLine3
        #   displayName: Run tests
        #   inputs:
        #     filename: $(CMakeBuildDirectory)\bin\$(BuildConfiguration)\ctest
        #     arguments: -C $(BuildConfiguration) -E "VSExcludeFromDefaultBuild-RelWithDebInfo|CMakeOnly.MajorVersionSelection-PythonInterp_2|RunCMake.AutoExportDll" --output-on-failure -E VSExcludeFromDefaultBuild-RelWithDebInfo
        #     workingFolder: $(CMakeBuildDirectory)
        - task: CopyFiles@2
          name: Copyzipx64
          displayName: Copy x64 zip
          inputs:
            SourceFolder:  $(CMakeBuildDirectory)
            Contents: 'cmake_install_x64.zip'
            TargetFolder: $(ArchiveDir)
            CleanTargetFolder: true
            OverWrite: true
        - task: DeleteFiles@1
          displayName: Delete CMake x64 Executables and ctresalloc.pdb
          inputs:
            SourceFolder: $(CMakeBuildDirectory)/bin/$(BuildConfiguration)/
            Contents: |-
              *.exe
              ctresalloc.pdb
        - task: ArchiveFiles@2
          displayName: Archive CMake x64 PDB Files
          inputs:
            rootFolderOrFile: $(CMakeBuildDirectory)/bin/$(BuildConfiguration)/
            archiveFile: $(Build.ArtifactStagingDirectory)/cmake_pdb_x64.zip
        - task: PowerShell@2
          displayName: Generate TSA config
          inputs:
            targetType: inline
            script: |
              $configName = "config.gdntsa"
              $config = @"
              {
                  "codebaseName": "MicrosoftCMake_cmake-daemon",
                  "notificationAliases": [
                      "cmake@microsoft.com"
                  ],
                  "codebaseAdmins": [
                      "NORTHAMERICA\\itodirel"
                  ],
                  "instanceUrl": "https://devdiv.visualstudio.com",
                  "projectName": "DevDiv",
                  "areaPath": "DevDiv\\Cpp Developer Experience\\Cross Platform\\CMake\\Upstream",
                  "iterationPath": "DevDiv\\Future Backlog",
                  "allTools": true
              }
              "@
              Out-File -FilePath "$(Agent.BuildDirectory)/$configName" -InputObject $config
        - task: PowerShell@2
          displayName: Create and Publish Version Tag
          inputs:
            targetType: inline
            script: |
              $cmd="$(CMakeInstallDirectory)/bin/cmake.exe --version"
              $version = "$(((Invoke-Expression $cmd) -Split " ")[2])"
              echo Creating Tag "v$version"
              git tag "v$version"
              git push origin "v$version"
      - job: Job_arm64
        displayName: CMake ARM64 Build
        timeoutInMinutes: 360
        cancelTimeoutInMinutes: 1
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish CMake ARM64 Artifact'
            targetPath: $(ArchiveDir)
            artifactName: CMakeArm64
        steps:
        - checkout: self
          clean: true
          fetchTags: false
        - task: CMake@1
          displayName: CMake ARM64 Cache Generation
          inputs:
            cwd: $(CMakeBuildDirectory)
            cmakeArgs: -DCMAKE_INSTALL_PREFIX:PATH=$(CMakeInstallDirectory) -DCMAKE_CONFIGURATION_TYPES=$(BuildConfiguration) -DCMake_VERSION_MICROSOFT_SCHEME=true -DCMake_VERSION_NO_GIT=true -DMicrosoft_CMake_VERSION_PATCH=$(Build.BuildNumber) -DCMAKE_CXX_FLAGS_INIT="/W3 /Qspectre /guard:cf /ZH:SHA_256" -DCMAKE_C_FLAGS_INIT="/W3 /Qspectre /guard:cf /ZH:SHA_256" -DCMAKE_EXE_LINKER_FLAGS_INIT="/incremental:no /profile /guard:cf" -S $(Build.SourcesDirectory) -B $(CMakeBuildDirectory) -G "Visual Studio 17 2022" -A ARM64 -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_ZIP=ON -DCPACK_PACKAGE_FILE_NAME=cmake_install_arm64
        - task: CMake@1
          displayName: CMake ARM64 Build and Package
          inputs:
            cwd: $(CMakeBuildDirectory)
            cmakeArgs: --build . --target package --config $(BuildConfiguration) -- -m
        - task: CopyFiles@2
          name: Copyziparm64
          displayName: Copy arm64 zip
          inputs:
            SourceFolder:  $(CMakeBuildDirectory)
            Contents: 'cmake_install_arm64.zip'
            TargetFolder: $(ArchiveDir)
            CleanTargetFolder: true
            OverWrite: true
        - task: DeleteFiles@1
          displayName: Delete CMake ARM64 Executables and ctresalloc.pdb
          inputs:
            SourceFolder: $(CMakeBuildDirectory)/bin/$(BuildConfiguration)/
            Contents: |-
              *.exe
              ctresalloc.pdb
        - task: ArchiveFiles@2
          displayName: Archive CMake ARM64 PDB Files
          inputs:
            rootFolderOrFile: $(CMakeBuildDirectory)/bin/$(BuildConfiguration)/
            archiveFile: $(ArchiveDir)/cmake_pdb_arm64.zip
      - job: Job_x86
        displayName: CMake x86 Build
        timeoutInMinutes: 360
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish CMake x86 Artifact'
            targetPath: $(ArchiveDir)
            artifactName: CMakeX86
        steps:
        - checkout: self
          clean: true
          fetchTags: false
        - task: CMake@1
          displayName: CMake x86 Cache Generation
          inputs:
            cwd: $(CMakeBuildDirectory)
            cmakeArgs: -DCMAKE_INSTALL_PREFIX:PATH=$(CMakeInstallDirectory) -DCMAKE_CONFIGURATION_TYPES=$(BuildConfiguration) -DCMake_VERSION_MICROSOFT_SCHEME=true -DCMake_VERSION_NO_GIT=true -DMicrosoft_CMake_VERSION_PATCH=$(Build.BuildNumber) -DCMAKE_CXX_FLAGS_INIT="/W3 /Qspectre /guard:cf /ZH:SHA_256" -DCMAKE_C_FLAGS_INIT="/W3 /Qspectre /guard:cf /ZH:SHA_256" -DCMAKE_EXE_LINKER_FLAGS_INIT="/incremental:no /profile /guard:cf /CETCOMPAT" -S $(Build.SourcesDirectory) -B $(CMakeBuildDirectory) -G "Visual Studio 17 2022" -A Win32 -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_ZIP=ON -DCPACK_PACKAGE_FILE_NAME=cmake_install_x86
        - task: CMake@1
          displayName: CMake x86 Build and Package
          inputs:
            cwd: $(CMakeBuildDirectory)
            cmakeArgs: --build . --target package --config $(BuildConfiguration) -- -m
        - task: CopyFiles@2
          name: Copyzipx86
          displayName: Copy x86 zip
          inputs:
            SourceFolder:  $(CMakeBuildDirectory)
            Contents: 'cmake_install_x86.zip'
            TargetFolder: $(ArchiveDir)
            CleanTargetFolder: true
            OverWrite: true
        - task: DeleteFiles@1
          displayName: Delete CMake x86 Executables and ctresalloc.pdb
          inputs:
            SourceFolder: $(CMakeBuildDirectory)/bin/$(BuildConfiguration)/
            Contents: |-
              *.exe
              ctresalloc.pdb
        - task: ArchiveFiles@2
          displayName: Archive CMake x86 PDB Files
          inputs:
            rootFolderOrFile: $(CMakeBuildDirectory)/bin/$(BuildConfiguration)/
            archiveFile: $(ArchiveDir)/cmake_pdb_x86.zip
