add_executable(app MACOSX_BUNDLE main.m)

set_target_properties(app PROPERTIES
  XCODE_EMBED_FRAMEWORKS "${EXTERNAL_FWK}"
  XCODE_EMBED_FRAMEWORKS_REMOVE_HEADERS_ON_COPY OFF
  XCODE_EMBED_FRAMEWORKS_CODE_SIGN_ON_COPY OFF
)
