include("${COUNT_FILE}" OPTIONAL)
if(NOT COUNT)
  set(COUNT 0)
endif()
math(EXPR COUNT "${COUNT} + 1")
file(WRITE "${COUNT_FILE}" "set(COUNT ${COUNT})\n")
if(NOT COUNT EQUAL 2)
  message(FATAL_ERROR "this test passes only on the 2nd run")
endif()
