include("${COUNT_FILE}" OPTIONAL)
if(NOT COUNT)
  set(COUNT 0)
endif()
math(EXPR COUNT "${COUNT} + 1")
file(WRITE "${COUNT_FILE}" "set(COUNT ${COUNT})\n")
if(NOT COUNT EQUAL 2)
  message("this test times out except on the 2nd run")
  execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 10)
endif()
