if(CMAKE_INSTALL_PREFIX)
  message("CMAKE_INSTALL_PREFIX is ${CMAKE_INSTALL_PREFIX}")
endif()

if(CMAKE_INSTALL_COMPONENT)
  message("CMAKE_INSTALL_COMPONENT is ${CMAKE_INSTALL_COMPONENT}")
endif()

if(CMAKE_INSTALL_CONFIG_NAME)
  message("CMAKE_INSTALL_CONFIG_NAME is ${CMAKE_INSTALL_CONFIG_NAME}")
endif()

if(CMAKE_INSTALL_DO_STRIP)
  message("CMAKE_INSTALL_DO_STRIP is ${CMAKE_INSTALL_DO_STRIP}")
endif()
