

add_subdirectory(subdir)

set_property(DIRECTORY PROPERTY LABELS L1 L2)

file(GENERATE OUTPUT DIRECTORY_PROPERTY-generated.txt CONTENT "SOURCE_DIR=$<DIRECTORY_PROPERTY:${CMAKE_CURRENT_SOURCE_DIR},SOURCE_DIR>\nSUBDIR_SOURCE_DIR=$<DIRECTORY_PROPERTY:${CMAKE_CURRENT_SOURCE_DIR}/subdir,SOURCE_DIR>\nLABELS=$<DIRECTORY_PROPERTY:${CMAKE_CURRENT_SOURCE_DIR},LABELS>\n")
