SET(CMAKE_DL_LIBS "")
SET(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-shared -rdata_shared")
SET(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-shared -rdata_shared") 
SET(CMAKE_SHARED_LIBRARY_RUNTIME_FLAG "-Wl,-rpath,")       # -rpath
SET(CMAKE_SHARED_LIBRARY_RUNTIME_FLAG_SEP "")   # : or empty
IF(NOT CMAKE_COMPILER_IS_GNUCXX)
  SET(CMAKE_CXX_CREATE_STATIC_LIBRARY
      "<CMAKE_CXX_COMPILER> -ar -o <TARGET> <OBJECTS>")
  SET(CMAKE_ANSI_CXXFLAGS -LANG:std)
  IF(NOT CMAKE_CXX_FLAGS)
    SET (CMAKE_CXX_FLAGS "")
    SET (CMAKE_CXX_FLAGS_DEBUG "-g")
    SET (CMAKE_CXX_FLAGS_MINSIZEREL "-O3")
    SET (CMAKE_CXX_FLAGS_RELEASE "-O2")
    SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2")
    SET (CMAKE_C_FLAGS "")
  ENDIF(NOT CMAKE_CXX_FLAGS)
ELSE(NOT CMAKE_COMPILER_IS_GNUCXX)
  INCLUDE(${CMAKE_ROOT}/Modules/Platform/gcc.cmake)
ENDIF(NOT CMAKE_COMPILER_IS_GNUCXX)

