if(CMAKE_SYSTEM MATCHES "MP-RAS-02*.")
  set(CMAKE_SHARED_LIBRARY_C_FLAGS "-K PIC")
else(CMAKE_SYSTEM MATCHES "MP-RAS-02*.")
  set(CMAKE_SHARED_LIBRARY_C_FLAGS "-K PIC")
  set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "-Wl,-Bexport")
endif(CMAKE_SYSTEM MATCHES "MP-RAS-02*.")

include(Platform/UnixPaths)


