include(Platform/Windows-MSVC)
set(_COMPILE_CXX " /TP")
if(NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 18.0)
  set(_FS_CXX " /FS")
endif()
__windows_compiler_msvc(CXX)
if(NOT MSVC_VERSION VERSION_LESS 1400)
  set(_cmake_feature_test_msvcxx_sealed "1")
endif()
