set(CMAKE_LINK_LIBRARY_SUFFIX "")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".l")
set(CMAKE_IMPORT_LIBRARY_SUFFIX ".l")
set(CMAKE_FIND_LIBRARY_PREFIXES "")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".l")

macro(__windows_compiler_orangec lang)
  set(CMAKE_${lang}_CREATE_WIN32_EXE "-Wg")
  set(CMAKE_${lang}_CREATE_CONSOLE_EXE "-Wc")

  if(CMAKE_C_COMPILER_VERSION VERSION_GREATER_EQUAL "7.0")
    if(NOT CMAKE_RC_COMPILER_INIT)
      set(CMAKE_RC_COMPILER_INIT orc)
    endif()
    enable_language(RC)
  endif()
endmacro()
