set(expect
  query
  query/client-client-member
  query/client-client-member/query.json
  query/client-empty-array
  query/client-empty-array/query.json
  query/client-empty-object
  query/client-empty-object/query.json
  query/client-json-bad-root
  query/client-json-bad-root/query.json
  query/client-json-empty
  query/client-json-empty/query.json
  query/client-json-extra
  query/client-json-extra/query.json
  query/client-not-file
  query/client-not-file/query.json
  query/client-request-array-negative-major-version
  query/client-request-array-negative-major-version/query.json
  query/client-request-array-negative-minor-version
  query/client-request-array-negative-minor-version/query.json
  query/client-request-array-negative-version
  query/client-request-array-negative-version/query.json
  query/client-request-array-no-major-version
  query/client-request-array-no-major-version/query.json
  query/client-request-array-no-supported-version
  query/client-request-array-no-supported-version-among
  query/client-request-array-no-supported-version-among/query.json
  query/client-request-array-no-supported-version/query.json
  query/client-request-array-version-1
  query/client-request-array-version-1-1
  query/client-request-array-version-1-1/query.json
  query/client-request-array-version-1/query.json
  query/client-request-array-version-2
  query/client-request-array-version-2/query.json
  query/client-request-negative-major-version
  query/client-request-negative-major-version/query.json
  query/client-request-negative-minor-version
  query/client-request-negative-minor-version/query.json
  query/client-request-negative-version
  query/client-request-negative-version/query.json
  query/client-request-no-major-version
  query/client-request-no-major-version/query.json
  query/client-request-no-version
  query/client-request-no-version/query.json
  query/client-request-version-1
  query/client-request-version-1-1
  query/client-request-version-1-1/query.json
  query/client-request-version-1/query.json
  query/client-request-version-2
  query/client-request-version-2/query.json
  query/client-requests-bad
  query/client-requests-bad/query.json
  query/client-requests-empty
  query/client-requests-empty/query.json
  query/client-requests-not-kinded
  query/client-requests-not-kinded/query.json
  query/client-requests-not-objects
  query/client-requests-not-objects/query.json
  query/client-requests-unknown
  query/client-requests-unknown/query.json
  reply
  reply/__test-v1-[0-9a-f]+.json
  reply/__test-v2-[0-9a-f]+.json
  reply/index-[0-9.T-]+.json
  )
check_api("^${expect}$")

check_python(ClientStateful)
