set(subdir ".o")
if (RunCMake_GENERATOR MATCHES "Visual Studio")
  set(subdir "CMakeFiles")
elseif (RunCMake_GENERATOR MATCHES "(Borland Makefiles|Watcom WMake)")
  set(subdir "_o")
endif ()
set(unitybuild_cxx "${RunCMake_TEST_BINARY_DIR}/${subdir}/9bc0d702/Unity/unity_0_cxx.cxx")
if(NOT EXISTS "${unitybuild_cxx}")
  set(RunCMake_TEST_FAILED "Generated unity source files ${unitybuild_cxx} does not exist.")
  return()
endif()
