set(obj "${RunCMake_TEST_BINARY_DIR}/UnityBuildPCH.dir/Debug/UnityBuildPCH.obj")
if(NOT EXISTS "${obj}")
  set(RunCMake_TEST_FAILED "Expected object file does not exist:\n  ${obj}")
  return()
endif()
set(lib "${RunCMake_TEST_BINARY_DIR}/Debug/UnityBuildPCH.lib")
if(EXISTS "${lib}")
  set(RunCMake_TEST_FAILED "Unexpected library file exists:\n  ${lib}")
  return()
endif()
