set(CMAKE_CONFIGURATION_TYPES Debug)
enable_language(C)
enable_language(CXX)

add_executable(DPIAWARE-default-C empty.c)
add_executable(DPIAWARE-default-CXX empty.cxx)

add_executable(DPIAWARE-TGT-PERMONITOR-C empty.c)
set_property(TARGET DPIAWARE-TGT-PERMONITOR-C PROPERTY VS_DPI_AWARE "PerMonitor")
add_executable(DPIAWARE-TGT-PERMONITOR-CXX empty.cxx)
set_property(TARGET DPIAWARE-TGT-PERMONITOR-CXX PROPERTY VS_DPI_AWARE "PerMonitor")
add_executable(DPIAWARE-TGT-ON-C empty.c)
set_property(TARGET DPIAWARE-TGT-ON-C PROPERTY VS_DPI_AWARE ON)
add_executable(DPIAWARE-TGT-ON-CXX empty.cxx)
set_property(TARGET DPIAWARE-TGT-ON-CXX PROPERTY VS_DPI_AWARE ON)
add_executable(DPIAWARE-TGT-OFF-C empty.c)
set_property(TARGET DPIAWARE-TGT-OFF-C PROPERTY VS_DPI_AWARE OFF)
add_executable(DPIAWARE-TGT-OFF-CXX empty.cxx)
set_property(TARGET DPIAWARE-TGT-OFF-CXX PROPERTY VS_DPI_AWARE OFF)
