enable_language(ISPC)
add_library(objs OBJECT obj1.ispc obj2.ispc)
if("${CMAKE_SYSTEM_NAME};${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "Darwin;arm64")
  set_property(TARGET objs PROPERTY ISPC_INSTRUCTION_SETS "neon-i32x4")
else()
  set_property(TARGET objs PROPERTY ISPC_INSTRUCTION_SETS "sse2-i32x4;sse4-i16x8;avx1-i32x16;avx2-i32x4")
endif()
install(FILES $<TARGET_OBJECTS:objs> DESTINATION objs)
