install(FILES main.c TYPE LOCALSTATE)
install(FILES main.c TYPE RUNSTATE)
install(FILES main.c TYPE DATA)
install(FILES main.c TYPE INFO)
install(FILES main.c TYPE LOCALE)
install(FILES main.c TYPE MAN)
install(FILES main.c TYPE DOC)
