set(vars CMAKE_SYSROOT CMAKE_SYSROOT_COMPILE CMAKE_SYSROOT_LINK CMAKE_FIND_ROOT_PATH)
foreach(v IN LISTS vars)
  set("${v}" "")
endforeach()
foreach(v IN LISTS vars)
  block()
    set("${v}" "/dummy")
    find_package(dummy CONFIG NO_DEFAULT_PATH PATHS "/")
  endblock()
endforeach()
