cmake_policy(VERSION 4.2)

file(GENERATE OUTPUT "STRGREATER_EQUAL-generated.txt"
              CONTENT "$<STRGREATER_EQUAL:A,AA>:$<STRGREATER_EQUAL:AA,BB>:$<STRGREATER_EQUAL:AA,AA>:$<STRGREATER_EQUAL:BB,AA>")
