set(SATU "/satu;/satu/CMakeLists.txt")
set(DUA "/dua;/dua/CMakeLists.txt")

if(GENERATOR_TYPE STREQUAL ZIP)
    set(_ext "zip")
elseif(GENERATOR_TYPE STREQUAL TGZ)
    set(_ext "tar.gz")
endif()

if(PACKAGING_TYPE STREQUAL "COMPONENT")
    set(EXPECTED_FILES_COUNT "2")
    set(EXPECTED_FILE_1 "*-satu.${_ext}")
    set(EXPECTED_FILE_CONTENT_1_LIST ${SATU})
    set(EXPECTED_FILE_2 "*-dua.${_ext}")
    set(EXPECTED_FILE_CONTENT_2_LIST ${DUA})
else()
    set(EXPECTED_FILES_COUNT "1")
    set(EXPECTED_FILE_CONTENT_1_LIST ${SATU} ${DUA})
endif()
