cmake_minimum_required(VERSION 4.0)
include(RunCMake)

if(RunCMake_GENERATOR MATCHES "Visual Studio 1[4-7]")
  include(${CMAKE_CURRENT_LIST_DIR}/solution_parsing.cmake)
  set(sln_ext "sln")
else()
  set(sln_ext "slnx")
endif()

run_cmake(DeployEnabled)
run_cmake(OnePre)
run_cmake(OnePost)
run_cmake(MorePre)
run_cmake(MorePost)
run_cmake(PrePost)
run_cmake(Override1)
run_cmake(Override2)
run_cmake(Override3)
run_cmake(SolutionItems)
run_cmake(StartupProject)
run_cmake(StartupProjectMissing)
run_cmake(AddPackageToDefault)

run_cmake(StartupProjectUseFolders)
run_cmake(CMP0143-WARN)
run_cmake_with_options(CMP0143-OLD "-DCMAKE_POLICY_DEFAULT_CMP0143=OLD")
run_cmake_with_options(CMP0143-NEW "-DCMAKE_POLICY_DEFAULT_CMP0143=NEW")
