if(NOT EXISTS "${lib}" OR NOT EXISTS "${exe_relink}" OR NOT EXISTS "${exe_no_relink}")
  file(REMOVE "${out}")
else()
  if("${exe_relink}" IS_NEWER_THAN "${lib}")
    file(WRITE "${out}" "1")
  else()
    file(WRITE "${out}" "0")
  endif()
  if("${exe_no_relink}" IS_NEWER_THAN "${lib}")
    file(APPEND "${out}" "1\n")
  else()
    file(APPEND "${out}" "0\n")
  endif()
endif()
