file(READ "${RunCMake_TEST_BINARY_DIR}/mytargets.cmake" mytargets)
if(NOT "${mytargets}" MATCHES "__find_dependency_no_return\\(P1")
  string(APPEND RunCMake_TEST_FAILED "P1 dependency should be exported but it is not\n")
endif()
if(NOT "${mytargets}" MATCHES "__find_dependency_no_return\\(P2")
  string(APPEND RunCMake_TEST_FAILED "P2 dependency should be exported but it is not\n")
endif()
if(NOT "${mytargets}" MATCHES "__find_dependency_no_return\\(P3")
  string(APPEND RunCMake_TEST_FAILED "P3 dependency should be exported but it is not\n")
endif()
if(NOT "${mytargets}" MATCHES "__find_dependency_no_return\\(P4")
  string(APPEND RunCMake_TEST_FAILED "P4 dependency should be exported but it is not\n")
endif()
