include("${RunCMake_SOURCE_DIR}/NoInstrumentationInCTestXML-check.cmake")

# Instrumentation should still produce snippets, but CTest must not look
# for their CDash staging copies when cdashSubmit has not been requested.
set(instrumentation_dir "${RunCMake_TEST_BINARY_DIR}/.cmake/instrumentation/v1")
if(ARGS_USE_STALE_CDASH)
  foreach(subdir configure build/commands build/targets/old-target)
    if(NOT EXISTS "${instrumentation_dir}/cdash/${subdir}/old.json")
      set(RunCMake_TEST_FAILED "Stale CDash snippet was consumed: ${subdir}/old.json")
      return()
    endif()
  endforeach()
elseif(EXISTS "${instrumentation_dir}/cdash")
  set(RunCMake_TEST_FAILED "Unexpected CDash staging directory")
  return()
endif()
file(GLOB snippets "${instrumentation_dir}/data/test-*.json")
list(LENGTH snippets count)
if(NOT count EQUAL 1)
  set(RunCMake_TEST_FAILED "Expected one local test snippet, found ${count}")
  return()
endif()
file(READ "${snippets}" snippet)
string(JSON role GET "${snippet}" role)
string(JSON test_name GET "${snippet}" testName)
if(NOT role STREQUAL "test" OR NOT test_name STREQUAL "main")
  set(RunCMake_TEST_FAILED "Unexpected local test snippet: ${snippet}")
endif()
