include("${RunCMake_SOURCE_DIR}/InstrumentationInCTestXML-check.cmake")

foreach(role compile link test)
  if(role STREQUAL "test")
    set(xml_type Test)
    set(element Results)
  else()
    set(xml_type Build)
    if(role STREQUAL "compile")
      set(element Compile)
    else()
      set(element Link)
    endif()
  endif()
  file(GLOB xml_file "${RunCMake_TEST_BINARY_DIR}/Testing/*/${xml_type}.xml")
  file(READ "${xml_file}" xml_content)
  string(REGEX MATCH "<${element}( [^>]*)?>.*</${element}>" measurements "${xml_content}")
  if(NOT measurements)
    set(RunCMake_TEST_FAILED "Missing ${element} element in ${xml_type}.xml")
    return()
  endif()
  file(READ "${RunCMake_TEST_BINARY_DIR}/metrics-${role}.json" snippet)
  string(JSON metrics GET "${snippet}" processMetrics)
  foreach(key maxRSS userTime systemTime)
    string(SUBSTRING "${key}" 0 1 first)
    string(TOUPPER "${first}" first)
    string(SUBSTRING "${key}" 1 -1 rest)
    set(name "${first}${rest}")
    string(JSON value ERROR_VARIABLE unavailable GET "${metrics}" ${key})
    if(unavailable)
      if(measurements MATCHES "name=\"${name}\"")
        set(RunCMake_TEST_FAILED "Unexpected ${name} measurement for ${role}")
        return()
      endif()
    elseif(NOT measurements MATCHES
        "<NamedMeasurement type=\"numeric/integer\" name=\"${name}\">[ \t\r\n]*<Value>${value}</Value>")
      set(RunCMake_TEST_FAILED "Expected ${name}=${value} measurement for ${role}")
      return()
    endif()
  endforeach()
endforeach()
