cmake_minimum_required(VERSION 4.3)

# Preserve the source snippets before CDash staging consumes them.
math(EXPR last_arg "${CMAKE_ARGC} - 1")
file(READ "${CMAKE_ARGV${last_arg}}" index)
string(JSON data_dir GET "${index}" dataDir)
string(JSON build_dir GET "${index}" buildDir)
string(JSON count LENGTH "${index}" snippets)
if(count GREATER 0)
  math(EXPR last "${count} - 1")
  foreach(i RANGE ${last})
    string(JSON filename GET "${index}" snippets ${i})
    file(READ "${data_dir}/${filename}" snippet)
    string(JSON role GET "${snippet}" role)
    if(role MATCHES "^(compile|link|test)$")
      file(COPY_FILE "${data_dir}/${filename}" "${build_dir}/metrics-${role}.json")
    endif()
  endforeach()
endif()
