include(RunCMake)

run_cmake(Always)
run_cmake(CompileSources)
run_cmake(Executable)
run_cmake(ImportedTargets)
run_cmake(LibraryArtifact)
run_cmake(Linkable)
run_cmake(NonImportedNormalTarget)
run_cmake(NonImportedTarget)
run_cmake(NormalTarget)
