if(RunCMake_GENERATOR MATCHES "Xcode")
  if (NOT actual_stdout MATCHES "-DOPT_SRC +-DOPT_FS")
    set (RunCMake_TEST_FAILED "Wrong compile options order.")
  endif()
else()
  if (NOT actual_stdout MATCHES "(/|-)D *OPT_TGT.+(/|-)D *OPT_SRC.+(/|-)D *OPT_FS")
    set (RunCMake_TEST_FAILED "Wrong compile options order.")
  endif()
endif()
