enable_language(C)

add_library(lib1 STATIC)
target_sources(lib1 PUBLIC FILE_SET a TYPE SOURCES FILES lib3.c)

set_property(FILE_SET a TARGET lib1 PROPERTY INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/dir")

if(NOT CMAKE_GENERATOR MATCHES "Xcode")
  set_property(TARGET lib1 PROPERTY INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/subdir1")
endif()
set_property(SOURCE lib3.c PROPERTY INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/subdir2")
