# Do not edit!  Generated by kwsysDateStamp.py
#=============================================================================
# KWSys - Kitware System Library
# Copyright 2000-2009 Kitware, Inc., Insight Software Consortium
#
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
#
# This software is distributed WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the License for more information.
#=============================================================================

# KWSys version date year component.  Format is CCYY.
SET(KWSYS_DATE_STAMP_YEAR  2010)

# KWSys version date month component.  Format is MM.
SET(KWSYS_DATE_STAMP_MONTH 03)

# KWSys version date day component.  Format is DD.
SET(KWSYS_DATE_STAMP_DAY   26)
