# ctest -C Debug: the Debug per-config include and the Debug-only conditional
# include both run; the Release per-config include does not.
if(NOT actual_stdout MATCHES "plain_test")
  string(APPEND RunCMake_TEST_FAILED "plain_test missing with -C Debug\n")
endif()
if(NOT actual_stdout MATCHES "indep_test")
  string(APPEND RunCMake_TEST_FAILED "indep_test missing with -C Debug\n")
endif()
if(NOT actual_stdout MATCHES "config_Debug")
  string(APPEND RunCMake_TEST_FAILED "config_Debug missing with -C Debug\n")
endif()
if(NOT actual_stdout MATCHES "dbgonly_test")
  string(APPEND RunCMake_TEST_FAILED "dbgonly_test missing with -C Debug\n")
endif()
if(RunCMake_GENERATOR_IS_MULTI_CONFIG)
  if(actual_stdout MATCHES "config_Release")
    string(APPEND RunCMake_TEST_FAILED "config_Release ran under -C Debug\n")
  endif()
endif()
