include(RunCMake)

# check syntax: add_custom_rule(... COMMAND ...)
run_cmake(NoArguments)
run_cmake(NoRuleName)
run_cmake(InvalidRuleName)
run_cmake(MissingRequiredOption-COMMAND)
run_cmake(MissingRequiredOption-OUTPUT)
run_cmake(MissingRequiredValues1)
run_cmake(MissingRequiredValues2)
run_cmake(InvalidDuplicateOption-DEPFILE)
run_cmake(InvalidDuplicateOption-CONFIGURATOR)
run_cmake(InvalidDuplicateOption-FOR_FILE_SET)
run_cmake(InvalidDuplicateOption-FOR_SOURCE)
run_cmake(InvalidValue1-FOR_FILE_SET)
run_cmake(InvalidValue2-FOR_FILE_SET)
run_cmake(InvalidValue1-FOR_SOURCE)
run_cmake(InvalidValue2-FOR_SOURCE)

# check syntax: add_custom_rule(... FROM_RULE ...)
run_cmake(FROM_RULE-NoRuleName)
run_cmake(FROM_RULE-MissingRequiredValue-FROM_RULE)
run_cmake(FROM_RULE-MissingRequiredValue-FOR_FILE_SET)
run_cmake(FROM_RULE-MissingRequiredValue-FOR_SOURCE)
run_cmake(FROM_RULE-InvalidOption-COMMAND)
run_cmake(FROM_RULE-InvalidOption-OUTPUT)
run_cmake(FROM_RULE-InvalidOption-DEPENDS)
run_cmake(FROM_RULE-InvalidOption-BYPRODUCTS)
run_cmake(FROM_RULE-InvalidOption-DEPFILE)
run_cmake(FROM_RULE-InvalidOption-FOR_FILE_SET)
run_cmake(FROM_RULE-InvalidOption-FOR_SOURCE)
run_cmake(FROM_RULE-InvalidDuplicateOption-CONFIGURATOR)
run_cmake(FROM_RULE-InvalidDuplicateOption-FOR_FILE_SET)
run_cmake(FROM_RULE-InvalidDuplicateOption-FOR_SOURCE)
run_cmake(FROM_RULE-InvalidValue-FROM_RULE)
run_cmake(FROM_RULE-InvalidValue1-FOR_FILE_SET)
run_cmake(FROM_RULE-InvalidValue2-FOR_FILE_SET)
run_cmake(FROM_RULE-InvalidValue1-FOR_SOURCE)
run_cmake(FROM_RULE-InvalidValue2-FOR_SOURCE)

# check rule creation
run_cmake(Rule-COMMAND)
run_cmake(Rule-OUTPUT)
run_cmake(Rule-DEPENDS)
run_cmake(Rule-BYPRODUCTS)
run_cmake(Rule-DEPFILE)
run_cmake(Rule-CONFIGURATOR)
run_cmake(Rule-GLOBAL)
run_cmake(RuleProperties)
