include(RunCMake)

block()
  set(RunCMake_TEST_OPTIONS -Wno-deprecated)
  run_cmake(PrintPropertiesArgForwarding)
  run_cmake(PrintPropertiesBackwardCompat)
  run_cmake(PrintPropertiesReservedKeywordPositionalArg)
  run_cmake(PrintPropertiesReservedKeywordPropertyName)
  run_cmake(VariablesArgForwarding)
  run_cmake(VariablesReservedKeyword)
endblock()
run_cmake(PrintPropertiesDeprecation)
run_cmake(VariablesDeprecation)
