enable_language(CXX)
set(CMAKE_CXX_INCLUDE_WHAT_YOU_USE "$<1:${PSEUDO_IWYU}>" -some -args)
set(CMAKE_CXX_CLANG_TIDY "$<1:${PSEUDO_TIDY}>" -some -args)
set(CMAKE_CXX_CPPLINT "$<1:${PSEUDO_CPPLINT}>" --verbose=0 --linelength=80)
set(CMAKE_CXX_CPPCHECK "$<1:${PSEUDO_CPPCHECK}>")
set(CMAKE_CXX_PVS_STUDIO "$<1:${PSEUDO_PVS}>" analyze)
add_executable(main main.cxx)
