include(RunCMake)

run_cmake(CMP0133-NEW)
run_cmake(CMP0133-WARN)
run_cmake(Simple)
run_cmake(Default)
run_cmake(Special)
run_cmake(Verbatim)
run_cmake(Version1)
run_cmake(Version2)
run_cmake(Version3)
