if(expectation STREQUAL "should_not_exist")
    set(should_exist FALSE)
elseif(expectation STREQUAL "should_exist")
    set(should_exist TRUE)
else()
    message(FATAL_ERROR "Encountered unknown expectation: ${expectation}")
endif()

if(EXISTS "${TARGET_FILE_tool_${config}}")
    if(NOT should_exist)
        message(FATAL_ERROR "${TARGET_FILE_tool_${config}} should not exist.")
    endif()
else()
    if(should_exist)
        message(FATAL_ERROR "${TARGET_FILE_tool_${config}} should exist.")
    endif()
endif()
