if(Python_EXECUTABLE AND CMake_TEST_JSON_SCHEMA)
  if(NOT CMakePresets_SCHEMA_EXPECTED_RESULT)
    set(CMakePresets_SCHEMA_EXPECTED_RESULT 0)
  endif()
  if(EXISTS "${RunCMake_TEST_SOURCE_DIR}/CMakePresets.json")
    validate_schema("${RunCMake_TEST_SOURCE_DIR}/CMakePresets.json" "${CMakePresets_SCHEMA_EXPECTED_RESULT}")
  endif()

  if(NOT CMakeUserPresets_SCHEMA_EXPECTED_RESULT)
    set(CMakeUserPresets_SCHEMA_EXPECTED_RESULT 0)
  endif()
  if(EXISTS "${RunCMake_TEST_SOURCE_DIR}/CMakeUserPresets.json")
    validate_schema("${RunCMake_TEST_SOURCE_DIR}/CMakeUserPresets.json" "${CMakeUserPresets_SCHEMA_EXPECTED_RESULT}")
  endif()

  if(NOT CMakePresets_EXTRA_FILES_SCHEMA_EXPECTED_RESULTS)
    set(CMakePresets_EXTRA_FILES_SCHEMA_EXPECTED_RESULTS "${_CMakePresets_EXTRA_FILES_SCHEMA_EXPECTED_RESULTS}")
  endif()
  foreach(_f _r IN ZIP_LISTS _CMakePresets_EXTRA_FILES_OUT CMakePresets_EXTRA_FILES_SCHEMA_EXPECTED_RESULTS)
    validate_schema("${_f}" "${_r}")
  endforeach()
endif()
