if(PYTHON_EXECUTABLE AND CMake_TEST_JSON_SCHEMA)
  if(NOT CMakePresets_SCHEMA_EXPECTED_RESULT)
    set(CMakePresets_SCHEMA_EXPECTED_RESULT 0)
  endif()
  if(EXISTS "${RunCMake_TEST_SOURCE_DIR}/CMakePresets.json")
    validate_schema("${RunCMake_TEST_SOURCE_DIR}/CMakePresets.json" "${CMakePresets_SCHEMA_EXPECTED_RESULT}")
  endif()

  if(NOT CMakeUserPresets_SCHEMA_EXPECTED_RESULT)
    set(CMakeUserPresets_SCHEMA_EXPECTED_RESULT 0)
  endif()
  if(EXISTS "${RunCMake_TEST_SOURCE_DIR}/CMakeUserPresets.json")
    validate_schema("${RunCMake_TEST_SOURCE_DIR}/CMakeUserPresets.json" "${CMakeUserPresets_SCHEMA_EXPECTED_RESULT}")
  endif()
endif()
