if (CMAKE_C_LINKER_WRAPPER_FLAG)
  set(linker_flag ${CMAKE_C_LINKER_WRAPPER_FLAG})
  list(GET linker_flag -1 linker_space)
  if (linker_space STREQUAL " ")
    list(REMOVE_AT linker_flag -1)
  else()
    set(linker_space)
  endif()
  list (JOIN linker_flag " " linker_flag)
  if (CMAKE_C_LINKER_WRAPPER_FLAG_SEP)
    set(linker_sep "${CMAKE_C_LINKER_WRAPPER_FLAG_SEP}")

    string (APPEND  linker_flag "${linker_space}" "-foo${linker_sep}bar")
  else()
    set(linker_prefix "${linker_flag}${linker_space}")

    set (linker_flag "${linker_prefix}-foo ${linker_prefix}bar")
  endif()
else()
  set(linker_flag "-foo bar")
endif()

file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/LINKER.txt" "${linker_flag}")
