include(RunCMake)

if(CMake_TEST_CLANG_COVERAGE)
  block()
    set(RunCMake_TEST_BINARY_DIR ${RunCMake_BINARY_DIR}/ClangCoverage-build)
    if(NOT RunCMake_GENERATOR_IS_MULTI_CONFIG)
      list(APPEND RunCMake_TEST_OPTIONS -DCMAKE_BUILD_TYPE=Debug)
    endif()
    run_cmake(ClangCoverage)
    set(RunCMake_TEST_NO_CLEAN 1)
    run_cmake_command(ClangCoverage-build ${CMAKE_COMMAND} --build . --config Debug)
    run_cmake_command(ClangCoverage-ctest ${CMAKE_CTEST_COMMAND} -C Debug -VV)
    run_cmake_command(ClangCoverage-coverage ${CMAKE_CTEST_COMMAND} -D ExperimentalCoverage -C Debug -VV)
  endblock()
endif()
