add_library(imported_var_global_target SHARED IMPORTED GLOBAL)
add_executable(imported_var_global_ex IMPORTED GLOBAL)

add_library(imported_var_local_target SHARED IMPORTED)
add_executable(imported_var_local_ex IMPORTED)
