if(GENERATOR_TYPE STREQUAL "DEB")
  set(CPACK_PACKAGE_CONTACT "someone")
  set(CPACK_DEB_COMPONENT_INSTALL "ON")

  set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
  set(CPACK_DEBIAN_PKG_2_PACKAGE_NAME "second")
  set(CPACK_DEBIAN_PKG_3_FILE_NAME "pkg_3_abc.deb")
elseif(GENERATOR_TYPE STREQUAL "RPM")
  set(CPACK_RPM_COMPONENT_INSTALL "ON")

  set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
  set(CPACK_RPM_PKG_2_PACKAGE_NAME "second")
  set(CPACK_RPM_PKG_3_FILE_NAME "pkg_3_abc.rpm")
endif()

install(FILES CMakeLists.txt DESTINATION foo COMPONENT pkg_1)
install(FILES CMakeLists.txt DESTINATION foo COMPONENT pkg_2)
install(FILES CMakeLists.txt DESTINATION foo COMPONENT pkg_3)
