set(CPACK_PACKAGE_CONTACT "someone")
set(CPACK_DEB_COMPONENT_INSTALL "ON")

set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PKG_2_PACKAGE_NAME "second")
set(CPACK_DEBIAN_PKG_3_FILE_NAME "pkg_3_abc.deb")
