/*=========================================================================

  Program:   Insight Segmentation & Registration Toolkit
  Module:    $RCSfile$
  Language:  C++
  Date:      $Date$
  Version:   $Revision$


  Copyright (c) 2000 National Library of Medicine
  All rights reserved.

  See COPYRIGHT.txt for copyright details.

=========================================================================*/
#ifndef cmWindowsConfigure_h
#define cmWindowsConfigure_h

#include "cmStandardIncludes.h"

/** \class cmWindowsConfigure
 * \brief Configure the build process on Windows systems.
 * 
 * cmWindowsConfigure configures the build process
 * on windows where the Unix autoconf configure can not be used.
 * The system specific .h files normally generated by autoconf
 * should be generated by sub-classes of this class.
 */
class cmWindowsConfigure
{
public:
  /**
   * Set the path to the top level of the source directory.
   */
  void SetWhereSource(const char* dir) 
    {
    m_WhereSource = dir;
    }

  /**
   * Set the path to the top level of the build directory.
   */
  void SetWhereBuild(const char* dir)
    {
      m_WhereBuild = dir;
    }

  /**
   * Perform the configure process.
   */
  virtual bool Configure(const char* input);

protected:
  std::string m_WhereSource;
  std::string m_WhereBuild;
};

#endif
