include(RunCMake)

run_cmake(Enable)
run_cmake(EnableExperimental)

block()
    set(RunCMake_TEST_BINARY_DIR ${RunCMake_BINARY_DIR}/Editions-build)
    run_cmake(Editions)
    set(RunCMake_TEST_NO_CLEAN 1)
    if (RunCMake_GENERATOR MATCHES "Ninja")
        run_cmake_command(Editions-build-Ninja ${CMAKE_COMMAND} --build . --config Debug)
    elseif(RunCMake_GENERATOR MATCHES "Makefiles")
        run_cmake_command(Editions-build-UnixMakefiles ${CMAKE_COMMAND} --build . --config Debug)
    else()
        message(FATAL_ERROR "Unsupported ${RunCMake_GENERATOR} generator!")
    endif()
endblock()
