enable_language(C)

set(vars
  CMAKE_C_COMPILER_WORKS
  CMAKE_C_COMPILER_ARCHITECTURE_ID
  CMAKE_C_STANDARD_INCLUDE_DIRECTORIES
  CMAKE_C_COMPILER_LINKER
  CMAKE_C_COMPILER_LINKER_ID
  CMAKE_C_COMPILER_LINKER_VERSION
  CMAKE_C_COMPILER_LINKER_FRONTEND_VARIANT
  CMAKE_C_IMPLICIT_LINK_LIBRARIES
  CMAKE_C_IMPLICIT_LINK_DIRECTORIES
  CMAKE_C_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES
  CMAKE_C_LIBRARY_ARCHITECTURE
  CMAKE_C_COMPILE_FEATURES
  CMAKE_C_USE_LINKER_INFORMATION)
foreach (std IN ITEMS 23 17 11 99 90)
  list(APPEND vars
     CMAKE_C${std}_COMPILE_FEATURES)
endforeach ()

include("${CMAKE_CURRENT_LIST_DIR}/write-toolchain.cmake")
