enable_language(CXX)

set(vars
  CMAKE_CXX_COMPILER_WORKS
  CMAKE_CXX_COMPILER_ARCHITECTURE_ID
  CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES
  CMAKE_CXX_COMPILER_LINKER
  CMAKE_CXX_COMPILER_LINKER_ID
  CMAKE_CXX_COMPILER_LINKER_VERSION
  CMAKE_CXX_COMPILER_LINKER_FRONTEND_VARIANT
  CMAKE_CXX_IMPLICIT_LINK_LIBRARIES
  CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES
  CMAKE_CXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES
  CMAKE_CXX_LIBRARY_ARCHITECTURE
  CMAKE_CXX_COMPILE_FEATURES
  CMAKE_CXX_USE_LINKER_INFORMATION

  CMAKE_CXX_COMPILER_IMPORT_STD
  CMAKE_CXX_STDLIB_MODULES_JSON)
foreach (std IN ITEMS 26 23 20 17 14 11 98)
  list(APPEND vars
     CMAKE_CXX${std}_COMPILE_FEATURES)
endforeach ()

include("${CMAKE_CURRENT_LIST_DIR}/write-toolchain.cmake")
