include(RunCMake)

run_cmake(add_custom_target)
run_cmake(add_custom_command)
run_cmake(add_link_options)
run_cmake(link_directories)
run_cmake(target_link_options)
run_cmake(target_link_directories)
run_cmake(invalid-property)
run_cmake(no-arguments)
run_cmake(empty-arguments)
run_cmake(forbidden-arguments)
run_cmake(invalid-feature)
run_cmake(multiple-definitions)
run_cmake(bad-feature1)
run_cmake(bad-feature2)
run_cmake(bad-feature3)
run_cmake(bad-feature4)
run_cmake(bad-feature5)
run_cmake(bad-feature6)
run_cmake(bad-feature7)
run_cmake(feature-not-supported)
run_cmake(library-ignored)
run_cmake(compatible-features)
run_cmake(incompatible-features1)
run_cmake(incompatible-features2)
run_cmake(incompatible-features3)
run_cmake(nested-compatible-features)
run_cmake(nested-incompatible-features)
run_cmake(only-targets)

# testing target properties LINK_LIBRARY_OVERRIDE and LINK_LIBRARY_OVERRIDE_<LIBRARY>
run_cmake(override-features1)
run_cmake(override-features2)
run_cmake(override-features3)
run_cmake(override-features4)
run_cmake(override-features5)

# testing feature attributes specification
run_cmake(bad-feature-attributes1)
run_cmake(bad-feature-attributes2)
run_cmake(bad-feature-attributes3)
run_cmake(bad-feature-attributes4)
run_cmake(bad-feature-attributes5)
run_cmake(unsupported-library_type)
run_cmake(cyclic-override)
run_cmake(multiple-override)
