include(RunCMake)

run_cmake(CMP0073)

run_cmake(INTERFACEwithNoSources)
run_cmake(OBJECTwithNoSources)
run_cmake(STATICwithNoSources)
run_cmake(SHAREDwithNoSources)
run_cmake(MODULEwithNoSources)
run_cmake(UNKNOWNwithNoSources)

run_cmake(INTERFACEwithOnlyObjectSources)
run_cmake(OBJECTwithOnlyObjectSources)
run_cmake(STATICwithOnlyObjectSources)
run_cmake(SHAREDwithOnlyObjectSources)
run_cmake(MODULEwithOnlyObjectSources)
run_cmake(UNKNOWNwithOnlyObjectSources)

run_cmake(INTERFACEwithNoSourcesButLinkObjects)
run_cmake(OBJECTwithNoSourcesButLinkObjects)
run_cmake(STATICwithNoSourcesButLinkObjects)
run_cmake(SHAREDwithNoSourcesButLinkObjects)
run_cmake(MODULEwithNoSourcesButLinkObjects)
run_cmake(UNKNOWNwithNoSourcesButLinkObjects)

run_cmake(TARGET_SUPPORTS_SHARED_LIBS_CMP0164_OLD)
run_cmake(TARGET_SUPPORTS_SHARED_LIBS_CMP0164_NEW)
run_cmake(TARGET_SUPPORTS_SHARED_LIBS_CMP0164_WARN)
