include(RunCMake)

run_cmake(InvalidArgs)
run_cmake(NoCompiler)
run_cmake(NoFeature)
run_cmake(FileTypo)
run_cmake(PrefixTypo)
run_cmake(ExtraArgs)
run_cmake(OldVersion)
run_cmake(InvalidCompiler)
run_cmake(InvalidFeature)
run_cmake(InvalidCXXFeature)
run_cmake(EmptyPrefix)
run_cmake(InvalidPrefix)
