if (NOT EXISTS ${RunCMake_TEST_BINARY_DIR}/.cmake/api/v1/reply)
  set(RunCMake_TEST_FAILED "Failed to read FileAPI query from user config directory")
endif()
if (NOT EXISTS ${RunCMake_TEST_BINARY_DIR}/.cmake/instrumentation-d16a3082-c4e1-489b-b90c-55750a334f27/v1/data)
  set(RunCMake_TEST_FAILED "Failed to read Instrumentation query from user config directory")
endif()
