if(GENERATOR_TYPE STREQUAL DEB)
  set(EXPECTED_FILE_1 "project_meta-1.2.3*.deb")
elseif(GENERATOR_TYPE STREQUAL RPM)
  set(EXPECTED_FILE_1 "project_meta-1.2.3*.rpm")
else()
  message(FATAL_ERROR "Unexpected CPack generator")
endif()
set(EXPECTED_FILES_COUNT "1")
set(EXPECTED_FILE_CONTENT_1_LIST "/foo;/foo/CMakeLists.txt")
