name: Build CMake for Android (armeabi-v7a) - Lengkap & Valid

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK, NDK, CMake
      run: |
        set -e
        export ANDROID_SDK_ROOT="${{ runner.temp }}/android-sdk"
        mkdir -p "$ANDROID_SDK_ROOT"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

        SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
        wget -O cmdline-tools.zip "$SDK_TOOLS_URL"
        unzip cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools-temp"
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        mv "$ANDROID_SDK_ROOT/cmdline-tools-temp/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
        rm -rf "$ANDROID_SDK_ROOT/cmdline-tools-temp"
        rm -f cmdline-tools.zip
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        which sdkmanager || { echo "sdkmanager tidak ditemukan"; exit 1; }
        yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --update
        yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
          "platforms;android-21" \
          "build-tools;33.0.0" \
          "ndk;r27" \
          "cmake;3.26.4"
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/r27" >> $GITHUB_ENV
        yes | sdkmanager --licenses --sdk_root="$ANDROID_SDK_ROOT"
        echo "SDK root: $ANDROID_SDK_ROOT"
        echo "NDK path: $ANDROID_NDK_HOME"

    - name: Verifikasi SDK & NDK setup
      run: |
        echo "Verifikasi keberadaan sdkmanager"
        which sdkmanager || echo "sdkmanager tidak ditemukan"
        echo "Isi folder SDK:"
        ls -l "$ANDROID_SDK_ROOT"
        echo "Isi folder NDK:"
        ls -l "$ANDROID_NDK_HOME"

    - name: Install build tools
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y cmake make ninja-build git

    - name: Clone CMake source code
      env:
        CMAKE_VERSION_TAG: "v3.29.3"
      run: |
        git clone --depth 1 --branch $CMAKE_VERSION_TAG https://github.com/Kitware/CMake.git ${{ runner.temp }}/cmake_src

    - name: Konfigurasi build CMake untuk Android armeabi-v7a
      env:
        CMAKE_BUILD_DIR: ${{ runner.temp }}/cmake_build_android
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
        INSTALL_DIR: ${{ runner.temp }}/cmake_android_install
      run: |
        mkdir -p "$CMAKE_BUILD_DIR"
        cd "$CMAKE_BUILD_DIR"
        export PATH=$PATH:${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin
        which sdkmanager || { echo "sdkmanager tidak ditemukan"; exit 1; }

        cmake "$CMAKE_SOURCE_DIR" \
          -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \
          -DANDROID_ABI=armeabi-v7a \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
          -DWITH_TESTING=OFF \
          -Wdev -Wdeprecated

        if [ $? -ne 0 ]; then
          echo "Konfigurasi CMake gagal!"
          exit 1
        fi

    - name: Build dengan make
      run: |
        cd "$CMAKE_BUILD_DIR"
        make -j$(nproc)

    - name: Install hasil build
      run: |
        cd "$CMAKE_BUILD_DIR"
        make install
        echo "Hasil instalasi:"
        ls -l "$INSTALL_DIR"

    - name: Upload artefak hasil build
      uses: actions/upload-artifact@v4
      with:
        name: cmake-android-armeabi-v7a
        path: "$INSTALL_DIR"
      if-no-files-found: error
