name: Build CMake for Android (armeabi-v7a)

on:
  # Ini memungkinkan Anda menjalankan workflow secara manual dari tab "Actions" di GitHub
  workflow_dispatch

jobs:
  build_android_armeabi_v7a:
    runs-on: ubuntu-latest # Menggunakan mesin virtual Ubuntu terbaru

    steps:
    - name: Checkout code
      # Mengunduh kode repositori (shantoze/CMake-arm) tempat workflow ini berada
      uses: actions/checkout@v4

    - name: Set up Java
      # NDK membutuhkan Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' # Versi Java yang kompatibel dengan NDK

    - name: Set up Android SDK and NDK
      # Menggunakan action komunitas untuk menginstal Android SDK dan NDK di runner
      # Ini akan menempatkan SDK di lokasi standar yang diketahui
      uses: android-sdk/setup-android@v0
      with:
        android-version: '35' # Menginstal SDK tools terbaru
        ndk: '29.0.13113456' # *** PENTING: Tentukan versi NDK yang konsisten di sini ***

    # Langkah ini biasanya tidak perlu karena cmake/make sudah ada di runner Ubuntu,
    # tapi bisa ditambahkan jika runner standar berubah.
    - name: Install Additional Build Tools (Optional, tapi disarankan)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make ninja-build git

    - name: Get CMake Source
      # Mengunduh kode sumber CMake LANGSUNG dari repositori asli Kitware
      # Disimpan di lokasi temporary runner ($RUNNER_TEMP/cmake_src)
      # Ini terpisah dari repositori shantoze/CMake-arm Anda
      run: git clone --depth 1 https://github.com/Kitware/CMake.git ${{ runner.temp }}/cmake_src

    - name: Create and Navigate to Build Directory
      # Membuat dan masuk ke direktori build di lokasi temporary
      run: |
        mkdir ${{ runner.temp }}/cmake_src/build
        cd ${{ runner.temp }}/cmake_src/build

    - name: Configure CMake Build for Android armeabi-v7a
      # Menjalankan konfigurasi CMake menggunakan NDK toolchain file dari instalasi NDK di runner
      env:
        # ANDROID_SDK_ROOT disetel oleh setup-android action
        # Menentukan path NDK berdasarkan lokasi instalasi action
        NDK_PATH: ${{ env.ANDROID_SDK_ROOT }}/ndk/29.0.13113456 # *** PENTING: Pastikan versi NDK cocok di sini ***
        INSTALL_DIR: ${{ runner.temp }}/cmake_install # Lokasi instalasi sementara di runner
      run: |
        cd ${{ runner.temp }}/cmake_src/build # Pastikan berada di direktori build
        cmake ${{ runner.temp }}/cmake_src \
          -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=armeabi-v7a \
          -DANDROID_PLATFORM=android-21 \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_MAKE_PROGRAM=$(which make)

    - name: Build CMake
      # Menjalankan proses kompilasi menggunakan make
      run: |
        cd ${{ runner.temp }}/cmake_src/build # Pastikan berada di direktori build
        make -j$(nproc) # Menggunakan semua core runner

    - name: Install CMake
      # Menyalin hasil build ke direktori instalasi sementara ($INSTALL_DIR)
      run: |
        cd ${{ runner.temp }}/cmake_src/build # Pastikan berada di direktori build
        make install

    - name: Archive built CMake
      # Mengunggah isi direktori instalasi sebagai artefak build yang bisa diunduh
      uses: actions/upload-artifact@v4
      with:
        name: cmake-android-armeabi-v7a # Nama file ZIP hasil yang diunduh
        path: ${{ runner.temp }}/cmake_install # Path direktori di runner yang akan diunggah
        # retention-days: 5 # Opsional: berapa lama artefak disimpan di GitHub
