name: Build CMake for Android (armeabi-v7a) - API 34

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build_android:
    runs-on: ubuntu-latest # Specifies the runner environment

    env:
      ANDROID_SDK_CMAKE_VERSION: "cmake;3.22.1" # Changed to a more common SDK CMake version
      ANDROID_NDK_VERSION_PACKAGE: "ndk;26.3.11579264" # NDK r26d
      CMAKE_VERSION_TAG: "v3.29.3" # Version of CMake to build (this is for the source we are compiling)
      ANDROID_PLATFORM: android-34 # <-- TARGET API LEVEL DIUBAH KE 34

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK, NDK, and SDK's CMake
      env:
        ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        set -e # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Setting ANDROID_SDK_ROOT"
        export ANDROID_SDK_ROOT="$ANDROID_SDK_ROOT"
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

        echo "Downloading Android command line tools..."
        SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
        wget -q -O cmdline-tools.zip "$SDK_TOOLS_URL"
        unzip -q cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools-temp"
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        mv "$ANDROID_SDK_ROOT/cmdline-tools-temp/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
        rm -rf "$ANDROID_SDK_ROOT/cmdline-tools-temp"
        rm -f cmdline-tools.zip

        echo "Adding SDK tools to PATH"
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" # Also for current script

        echo "Verifying sdkmanager..."
        which sdkmanager || { echo "sdkmanager not found on PATH after setup."; exit 1; }

        echo "Updating SDK (verbose)..."
        # Removed > /dev/null to see output from sdkmanager --update
        yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --update

        echo "Installing NDK ('${{ env.ANDROID_NDK_VERSION_PACKAGE }}'), platforms, build-tools, SDK's CMake ('${{ env.ANDROID_SDK_CMAKE_VERSION }}')..."
        yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
          "platforms;${{ env.ANDROID_PLATFORM }}" \
          "build-tools;33.0.0" \
          "${{ env.ANDROID_NDK_VERSION_PACKAGE }}" \
          "${{ env.ANDROID_SDK_CMAKE_VERSION }}" # <-- Mungkin ini baris 54 Anda di file Anda. Pastikan indentasinya 8 spasi dan tidak ada spasi setelah '\' di baris atasnya.

        echo "Attempting to locate installed NDK..." # <-- Baris setelah perintah sdkmanager
        NDK_BASE_PATH="$ANDROID_SDK_ROOT/ndk"
        if [ ! -d "$NDK_BASE_PATH" ] || [ -z "$(ls -A $NDK_BASE_PATH)" ]; then
        # ... dan seterusnya ...

    # ... langkah-langkah lainnya seperti Verify SDK & NDK setup, Install build tools, Clone CMake ...

    # --- START: Langkah patching baru untuk menonaktifkan include android_lf.h (Menggunakan 2 sed) ---
    - name: Patch cmlibarchive archive.h to disable android_lf.h include (two sed commands)
      env:
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        ARCHIVE_H_PATH="$CMAKE_SOURCE_DIR/Utilities/cmlibarchive/libarchive/archive.h" # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Patching $ARCHIVE_H_PATH to disable android_lf.h include using two separate sed commands."

        # Cari baris `#include "android_lf.h"` dan sisipkan #if 0 sebelum itu
        sed -i '/#include "android_lf.h"/i#if 0' "$ARCHIVE_H_PATH" # <-- Perhatikan indentasi di sini (8 spasi)

        # Cari baris `#include "android_lf.h"` (yang sekarang ada setelah #if 0) dan tambahkan #endif setelah itu
        sed -i '/#include "android_lf.h"/a#endif' "$ARCHIVE_H_PATH" # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Patch applied. Showing relevant section of archive.h:" # <-- Perhatikan indentasi di sini (8 spasi)
        # Tampilkan bagian yang di-patch untuk verifikasi
        grep -A 2 -B 1 "android_lf.h" "$CMAKE_SOURCE_DIR/Utilities/cmlibarchive/libarchive/archive.h" || echo "Could not find patched section using grep." # <-- Perhatikan indentasi di sini (8 spasi)
    # --- END: Langkah patching android_lf.h ---

    # --- START: Langkah Verifikasi Patch archive.h ---
    - name: Verify cmlibarchive archive.h patch
      env:
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        ARCHIVE_H_PATH="$CMAKE_SOURCE_DIR/Utilities/cmlibarchive/libarchive/archive.h" # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Verifying patch in $ARCHIVE_H_PATH..." # <-- Perhatikan indentasi di sini (8 spasi)
        # Periksa apakah #if 0 ada tepat sebelum baris include
        # Menggunakan pcregrep untuk pola yang lebih canggih yang mencari #if 0 diikuti *langsung* oleh include di baris berikutnya
        if pcregrep -q '#if 0\n#include "android_lf.h"' "$ARCHIVE_H_PATH"; then # <-- Perhatikan indentasi di sini (8 spasi)
           echo "Patch start (#if 0) found correctly before include." # <-- Perhatikan indentasi di sini (11 spasi)
        else # <-- Perhatikan indentasi di sini (8 spasi)
           echo "Error: Patch start (#if 0) NOT found correctly before include." # <-- Perhatikan indentasi di sini (11 spasi)
           echo "Content of $ARCHIVE_H_PATH:" # <-- Perhatikan indentasi di sini (11 spasi)
           cat "$ARCHIVE_H_PATH" # Dump the file content for inspection # <-- Perhatikan indentasi di sini (11 spasi)
           exit 1 # <-- Perhatikan indentasi di sini (11 spasi)
        fi # <-- Perhatikan indentasi di sini (8 spasi)
        # Periksa apakah #endif ada tepat setelah baris include
        # Menggunakan pcregrep untuk pola yang lebih canggih yang mencari include diikuti *langsung* oleh #endif di baris berikutnya
        if pcregrep -q '#include "android_lf.h"\n#endif' "$ARCHIVE_H_PATH"; then # <-- Perhatikan indentasi di sini (8 spasi)
           echo "Patch end (#endif) found correctly after include." # <-- Perhatikan indentasi di sini (11 spasi)
        else # <-- Perhatikan indentasi di sini (8 spasi)
           echo "Error: Patch end (#endif) NOT found correctly after include." # <-- Perhatikan indentasi di sini (11 spasi)
           echo "Content of $ARCHIVE_H_PATH:" # <-- Perhatikan indentasi di sini (11 spasi)
           cat "$ARCHIVE_H_PATH" # Dump the file content for inspection # <-- Perhatikan indentasi di sini (11 spasi)
           exit 1 # <-- Perhatikan indentasi di sini (11 spasi)
        fi # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Patch verification complete." # <-- Perhatikan indentasi di sini (8 spasi)
    # --- END: Langkah Verifikasi Patch archive.h ---


    # --- START: Langkah patching untuk memperbaiki error sched.h (core.c) ---
    - name: Patch cmlibuv core.c for sched.h includes
      env:
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        echo "Patching Utilities/cmlibuv/src/unix/core.c to include sched.h" # <-- Perhatikan indentasi di sini (8 spasi)
        # Menggunakan sed untuk menyisipkan baris di awal file
        # Sisipkan #define _GNU_SOURCE di baris 1
        sed -i '1i#define _GNU_SOURCE' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/core.c" # <-- Perhatikan indentasi di sini (8 spasi)
        # Sisipkan #include <sched.h> di baris 2 (yang kini berada setelah define)
        sed -i '2i#include <sched.h>' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/core.c" # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Patch applied. Showing first few lines of core.c:" # <-- Perhatikan indentasi di sini (8 spasi)
        head "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/core.c" # <-- Perhatikan indentasi di sini (8 spasi)
    # --- END: Langkah patching sched.h ---

    # --- START: Langkah patching untuk memperbaiki error pipe2 (pipe.c) ---
    - name: Patch cmlibuv pipe.c for unistd.h and pipe2 define
      env:
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        echo "Patching Utilities/cmlibuv/src/unix/pipe.c to include unistd.h and define _GNU_SOURCE" # <-- Perhatikan indentasi di sini (8 spasi)
        # Menggunakan sed untuk menyisipkan baris di awal file
        # Sisipkan #define _GNU_SOURCE di baris 1
        sed -i '1i#define _GNU_SOURCE' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/pipe.c" # <-- Perhatikan indentasi di sini (8 spasi)
        # Sisipkan #include <unistd.h> di baris 2
        sed -i '2i#include <unistd.h>' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/pipe.c" # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Patch applied. Showing first few lines of pipe.c:" # <-- Perhatikan indentasi di sini (8 spasi)
        head "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/pipe.c" # <-- Perhatikan indentasi di sini (8 spasi)
    # --- END: Langkah patching pipe2 ---

    # --- START: Langkah patching untuk memperbaiki error CPU affinity (process.c) ---
    - name: Patch cmlibuv process.c for sched.h, pthread.h, defines, and stub for pthread_setaffinity_np (revised sed)
      env:
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        echo "Patching Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
        # Tambahkan define dan include di bagian paling atas
        sed -i '1i#define _GNU_SOURCE' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
        sed -i '2i#include <sched.h>' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
        sed -i '3i#include <pthread.h>' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)

        # Tambahkan deklarasi kondisional untuk pthread_setaffinity_np jika belum dideklarasikan
        # Sisipkan baris demi baris menggunakan perintah sed terpisah
        sed -i '4i#ifndef pthread_setaffinity_np' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
        sed -i '5i#warning "Using stub pthread_setaffinity_np - actual function may be missing or require different defines"' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
        sed -i '6iint pthread_setaffinity_np(pthread_t, size_t, const cpu_set_t *);' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
        sed -i '7i#endif' "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Patch applied. Showing first few lines of process.c:" # <-- Perhatikan indentasi di sini (8 spasi)
        head "$CMAKE_SOURCE_DIR/Utilities/cmlibuv/src/unix/process.c" # <-- Perhatikan indentasi di sini (8 spasi)
    # --- END: Langkah patching process.c ---


    - name: Konfigurasi build CMake untuk Android armeabi-v7a
      env:
        CMAKE_BUILD_DIR: ${{ runner.temp }}/cmake_build_android
        CMAKE_SOURCE_DIR: ${{ runner.temp }}/cmake_src
        INSTALL_DIR: ${{ runner.temp }}/cmake_android_install
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        echo "Configuring CMake build for Android (armeabi-v7a)..." # <-- Perhatikan indentasi di sini (8 spasi)
        mkdir -p "$CMAKE_BUILD_DIR" # <-- Perhatikan indentasi di sini (8 spasi)
        cd "$CMAKE_BUILD_DIR" # <-- Perhatikan indentasi di sini (8 spasi)

        export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH" # <-- Perhatikan indentasi di sini (8 spasi)
        which sdkmanager > /dev/null || echo "Warning: sdkmanager not found during CMake configuration." # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Using NDK from: $ANDROID_NDK_HOME" # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Toolchain file will be: $ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Targeting Android API level: ${{ env.ANDROID_PLATFORM }}" # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Targeting Android ABI: armeabi-v7a" # <-- Perhatikan indentasi di sini (8 spasi)

        # This cmake command uses the host's cmake (installed in previous step)
        # to configure the build of CMake sources for Android.
        # PASTIKAN TIDAK ADA SPASI SETELAH BACKSLASH DI SETIAP AKHIR BARIS DI BAWAH INI
        cmake "$CMAKE_SOURCE_DIR" \ # <-- Perhatikan indentasi di sini (8 spasi)
              -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \ # <-- Perhatikan indentasi di sini (14 spasi)
              -DANDROID_ABI=armeabi-v7a \ # <-- Perhatikan indentasi di sini (14 spasi)
              -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }} \ # <-- Perhatikan indentasi di sini (14 spasi)
              -DCMAKE_BUILD_TYPE=Release \ # <-- Perhatikan indentasi di sini (14 spasi)
              -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \ # <-- Perhatikan indentasi di sini (14 spasi)
              -DBUILD_TESTING=OFF \ # <-- Perhatikan indentasi di sini (14 spasi)
              -Wno-dev # <-- Perhatikan indentasi di sini (14 spasi)

        if [ $? -ne 0 ]; then # <-- Perhatikan indentasi di sini (8 spasi)
          echo "CMake configuration failed!" # <-- Perhatikan indentasi di sini (11 spasi)
          echo "CMakeOutput.log content:" # <-- Perhatikan indentasi di sini (11 spasi)
          cat "$CMAKE_BUILD_DIR/CMakeFiles/CMakeOutput.log" || echo "CMakeOutput.log not found." # <-- Perhatikan indentasi di sini (11 spasi)
          echo "CMakeError.log content:" # <-- Perhatikan indentasi di sini (11 spasi)
          cat "$CMAKE_BUILD_DIR/CMakeFiles/CMakeError.log" || echo "CMakeError.log not found." # <-- Perhatikan indentasi di sini (11 spasi)
          exit 1 # <-- Perhatikan indentasi di sini (11 spasi)
        fi # <-- Perhatikan indentasi di sini (8 spasi)
        echo "CMake configuration successful." # <-- Perhatikan indentasi di sini (8 spasi)

    - name: Build CMake with make
      env:
        CMAKE_BUILD_DIR: ${{ runner.temp }}/cmake_build_android
        INSTALL_DIR: ${{ runner.temp }}/cmake_android_install
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        echo "Building CMake using make..." # <-- Perhatikan indentasi di sini (8 spasi)
        cd "$CMAKE_BUILD_DIR" # <-- Perhatikan indentasi di sini (8 spasi)
        make -j$(nproc) # <-- Perhatikan indentasi di sini (8 spasi)
        if [ $? -ne 0 ]; then # <-- Perhatikan indentasi di sini (8 spasi)
          echo "Make build failed!" # <-- Perhatikan indentasi di sini (11 spasi)
          exit 1 # <-- Perhatikan indentasi di sini (11 spasi)
        fi # <-- Perhatikan indentasi di sini (8 spasi)
        echo "Make build successful." # <-- Perhatikan indentasi di sini (8 spasi)

    - name: Install hasil build CMake
      env:
        CMAKE_BUILD_DIR: ${{ runner.temp }}/cmake_build_android
        INSTALL_DIR: ${{ runner.temp }}/cmake_android_install
      run: | # <-- Perhatikan indentasi di sini (6 spasi)
        echo "Installing CMake to $INSTALL_DIR..." # <-- Perhatikan indentasi di sini (8 spasi)
        cd "$CMAKE_BUILD_DIR" # <-- Perhatikan indentasi di sini (8 spasi)
        make install # <-- Perhatikan indentasi di sini (8 spasi)
        if [ $? -ne 0 ]; then # <-- Perhatikan indentasi di sini (8 spasi)
          echo "Make install failed!" # <-- Perhatikan indentasi di sini (11 spasi)
          exit 1 # <-- Perhatikan indentasi di sini (11 spasi)
        fi # <-- Perhatikan indentasi di sini (8 spasi)
        echo "CMake installation successful. Contents of $INSTALL_DIR:" # <-- Perhatikan indentasi di sini (8 spasi)
        ls -lA "$INSTALL_DIR" # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Verifying key directories in installation:" # <-- Perhatikan indentasi di sini (8 spasi)
        ls -lA "$INSTALL_DIR/bin" || echo "Warning: $INSTALL_DIR/bin not found or empty." # <-- Perhatikan indentasi di sini (8 spasi)

        CMAKE_VERSION_NUMERIC_PART="${CMAKE_VERSION_TAG#v}" # <-- Perhatikan indentasi di sini (8 spasi)
        CMAKE_SHARE_DIR_VERSION=$(echo "$CMAKE_VERSION_NUMERIC_PART" | cut -d. -f1,2) # <-- Perhatikan indentasi di sini (8 spasi)
        CMAKE_SHARE_DIR_TO_CHECK="cmake-$CMAKE_SHARE_DIR_VERSION" # <-- Perhatikan indentasi di sini (8 spasi)

        echo "Verifying share directory: $INSTALL_DIR/share/$CMAKE_SHARE_DIR_TOCHECK" # <-- Perhatikan indentasi di sini (8 spasi)
        ls -lA "$INSTALL_DIR/share/$CMAKE_SHARE_DIR_TO_CHECK" || echo "Warning: $INSTALL_DIR/share/$CMAKE_SHARE_DIR_TO_CHECK not found or empty." # <-- Perhatikan indentasi di sini (8 spasi)

    - name: Upload artefak hasil build
      uses: actions/upload-artifact@v4
      with:
        name: cmake-${{ env.CMAKE_VERSION_TAG }}-android-armeabi-v7a-ndk${{ env.NDK_VERSION_NUMBER_FOR_ARTIFACT }}-api${{ env.ANDROID_PLATFORM }}
        path: ${{ runner.temp }}/cmake_android_install
        if-no-files-found: error
