set(CMake_ENABLE_INSTRUMENTATION "ON" CACHE BOOL "")
set(CMake_TEST_GUI "OFF" CACHE BOOL "")
set(CMAKE_EXPERIMENTAL_INSTRUMENTATION "ec7aa2dc-b87f-45a3-8022-fe01c5f59984" CACHE STRING "")
include("${CMAKE_CURRENT_LIST_DIR}/configure_fedora43_ninja.cmake")
