set(CMake_TEST_FindBLAS "All;Intel10_64lp;Intel10_64lp.gcc" CACHE STRING "")
set(CMake_TEST_FindBLAS_All "Intel10_64lp" CACHE STRING "")
set(CMake_TEST_FindBLAS_STATIC "All;Intel10_64lp;Intel10_64lp.gcc" CACHE STRING "")
set(CMake_TEST_FindBLAS_STATIC_All "Intel10_64lp" CACHE STRING "")
set(CMake_TEST_FindLAPACK "All;Intel10_64lp;Intel10_64lp.gcc" CACHE STRING "")
set(CMake_TEST_FindLAPACK_All "Intel10_64lp" CACHE STRING "")
set(CMake_TEST_FindLAPACK_STATIC "All;Intel10_64lp;Intel10_64lp.gcc" CACHE STRING "")
set(CMake_TEST_FindLAPACK_STATIC_All "Intel10_64lp" CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/configure_external_test.cmake")
