include(RunCMake)

run_cmake(DEVICE_LINK-add_custom_target)
run_cmake(DEVICE_LINK-add_custom_command)
run_cmake(DEVICE_LINK-install)
run_cmake(DEVICE_LINK-add_executable)
run_cmake(DEVICE_LINK-add_library)
run_cmake(DEVICE_LINK-add_test)
run_cmake(DEVICE_LINK-target_sources)
run_cmake(DEVICE_LINK-target_compile_definitions)
run_cmake(DEVICE_LINK-target_compile_options)
run_cmake(DEVICE_LINK-target_include_directories)
run_cmake(DEVICE_LINK-target_link_libraries)
run_cmake(DEVICE_LINK-target_link_directories)
if(RunCMake_GENERATOR MATCHES "(Ninja|Makefile)")
  run_cmake(DEVICE_LINK-link_depends)
endif()
