include(RunCMake)

run_cmake(add_custom_target)
run_cmake(add_custom_command)
run_cmake(install)
run_cmake(add_executable)
run_cmake(add_library)
run_cmake(add_test)
run_cmake(target_sources)
run_cmake(target_compile_definitions)
run_cmake(target_compile_options)
run_cmake(target_include_directories)
run_cmake(target_link_libraries)
run_cmake(target_link_directories)
run_cmake(try_compile)
if(RunCMake_GENERATOR MATCHES "(Ninja|Makefile)")
  run_cmake(link_depends)
endif()
